<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2_3</name>
   <tag></tag>
   <elementGuidId>ff77fc4d-d2b9-4950-8565-d5c5fc22122e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.withdrawal_balance.btn.btn-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='removable2']/td[11]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71295860-cb72-494a-b620-0a791d13d996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientbalance</name>
      <type>Main</type>
      <value>8,000.00</value>
      <webElementGuid>1f4e17bb-ac93-4e4e-a4de-e310a354390a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientname</name>
      <type>Main</type>
      <value>سعفان</value>
      <webElementGuid>7a14064b-41a1-4b7e-9c0e-de2ba0ab3b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5179ec6a-ed2d-46cf-9813-d9be1c7f5edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withdrawal_balance btn btn-danger</value>
      <webElementGuid>a0721c8e-86d9-47be-adca-31cd14c41593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>سحب رصيد</value>
      <webElementGuid>a338dace-de51-4ce0-abe9-b5175d82aefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;removable2&quot;)/td[11]/button[@class=&quot;withdrawal_balance btn btn-danger&quot;]</value>
      <webElementGuid>e3183c38-8ccd-46d7-bb4d-f3d6c2b1a89f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='removable2']/td[11]/button</value>
      <webElementGuid>e3390026-fff0-4497-889e-6a1362efda6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اضافة رصيد'])[2]/following::button[1]</value>
      <webElementGuid>8d7533b4-250a-486d-a680-9ed2abea22ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نشط'])[1]/following::button[2]</value>
      <webElementGuid>771c8641-7ab4-4005-b75f-109e2af16e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تعديل'])[1]/preceding::button[1]</value>
      <webElementGuid>31bc309c-b4a7-415c-bd26-246c5ac532fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تغيير الحالة'])[1]/preceding::button[1]</value>
      <webElementGuid>bdb275f7-296f-4496-8767-d6daffaa4c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/button</value>
      <webElementGuid>aaabd9a6-00fb-45c7-bef1-45194c2c524a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'سحب رصيد' or . = 'سحب رصيد')]</value>
      <webElementGuid>a8aa0f7f-fd3a-4e40-a476-7e53d9ee7c9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
