<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__balance_1</name>
   <tag></tag>
   <elementGuidId>bbcf76b4-8b07-46a8-badf-93a231bf7a5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#withdrawal_balance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='withdrawal_balance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9860b90-3891-4336-8582-ae1af6bf902f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdrawal_balance</value>
      <webElementGuid>5ae16317-61b4-4ab5-b2bf-7ffce6dcb9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>balance</value>
      <webElementGuid>46a54e46-23f4-45af-848a-b73492a9a950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fd82887d-71fc-4f19-a1af-cd26c498ba22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>97375511-7250-4d56-bbba-23ac8d725786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e31b2043-da68-4621-b45a-3829d048277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>70590830-b9c3-48b2-96a6-94468d343bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdrawal_balance&quot;)</value>
      <webElementGuid>463a4db5-dc3f-4951-9b5b-87cee2458434</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='withdrawal_balance']</value>
      <webElementGuid>7d992fae-f71c-41f4-acf2-e6c00938ed3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='client_withdrawal_balance']/div/div/form/div/div[3]/input</value>
      <webElementGuid>881b464e-cb58-4cd9-baa0-ecc90f665195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div/div[3]/input</value>
      <webElementGuid>60811ccd-c669-4fb7-ab4a-27bec106bd21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'withdrawal_balance' and @name = 'balance' and @type = 'number']</value>
      <webElementGuid>e0584b66-e4e3-469e-bff1-15826b43fd31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
