<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>79578ed1-d587-416e-b74a-bfea93eb0639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bill-form-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='bill-form-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70ba1446-1b47-48d7-9726-871c1a60d7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bill-form-submit</value>
      <webElementGuid>44d12548-e11d-46ca-9079-d639810e6c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d530b088-59bd-447f-9616-1d97155fd8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>952e6509-d82b-418a-88ea-fe90b546276c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>حفظ</value>
      <webElementGuid>ffaeb3a9-3b1e-4c83-8d83-eefe456e7b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bill-form-submit&quot;)</value>
      <webElementGuid>aedf4ddd-ea13-426c-be0b-e581d2f2fbcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='bill-form-submit']</value>
      <webElementGuid>4ec54dd1-c567-4519-9e0c-5b8e165000fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='bill-form']/div[2]/div/div/div/div/div/div/button</value>
      <webElementGuid>52165578-ae16-45cc-8272-a1fa75ae60c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاجمالي'])[1]/following::button[1]</value>
      <webElementGuid>1ac08191-6af7-484e-8d7e-aef882a82b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قماشة فرامل كبيرة'])[2]/following::button[1]</value>
      <webElementGuid>51ef24dd-e1f1-41a5-9d91-d977d45bb47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'bill-form-submit', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>5968fb7f-8270-42cd-872a-1d99403f453c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='حفظ']/parent::*</value>
      <webElementGuid>fc0a01a1-3364-4289-86cc-70f7fb77475e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>67544334-3c60-48e0-af24-c6260af43df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'bill-form-submit' and @type = 'submit' and (text() = 'حفظ' or . = 'حفظ')]</value>
      <webElementGuid>a6f68d0f-4ea9-43d5-a699-61b178e69e61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
