<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__number</name>
   <tag></tag>
   <elementGuidId>ce9d82d3-bd7c-457a-a219-89cdadec5d4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac23fa40-b5f5-4e11-82f4-73b584d88e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c0f750f9-d955-4b8e-a453-6b84f6410cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>bab9f5a2-566e-456a-aa0d-283c69ef52f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed151078-2e5d-48ea-b49b-586334df18c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>2c11b0ca-01ae-4438-8691-c9b5afbcf9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number&quot;)</value>
      <webElementGuid>3b5ec6a7-16c5-4713-9b84-fe56e23dca36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number']</value>
      <webElementGuid>5ec78722-0e0a-4a45-b42d-0614ec629945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='bill-form']/div/div/div/div[3]/div/input</value>
      <webElementGuid>8f1b743c-f303-4149-a1ab-8623603783e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>ea174236-caef-4116-ba8e-fc6f8a1d2c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'number' and @name = 'number' and @type = 'text']</value>
      <webElementGuid>9e598abb-3463-4cd7-aba7-352ae8f9cb5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
