<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>d8dea288-5f98-4bbc-a286-94708dc77a4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save_print</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save_print']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>328d4bc4-2597-4d17-97fe-50159c314995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 btn  btn-success</value>
      <webElementGuid>128f8636-1549-4fc7-af3a-7651b98234c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>179d1eaf-db59-4ab8-81f7-6b39be85aed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_print</value>
      <webElementGuid>17e1b71a-ea35-440c-a647-a2f0e6519cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>حفظ
                        </value>
      <webElementGuid>0eaeb155-f39d-42b5-bd47-c13598c8ab8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_from&quot;)/button[@id=&quot;save_print&quot;]</value>
      <webElementGuid>6f5e48f2-4d1e-43d8-9a44-6afd197dbdbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save_print']</value>
      <webElementGuid>6e3add14-78f6-4544-abd0-a160929b0719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add_from']/button</value>
      <webElementGuid>e520fd36-869f-48e5-b803-82c03e508bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نشط /غير نشط'])[1]/following::button[1]</value>
      <webElementGuid>23d6c8b9-d848-4043-8626-c89debf5d195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاسم بالانجليزية'])[1]/following::button[1]</value>
      <webElementGuid>d14efb35-8319-4a92-b12b-d3b1dbaf81ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/preceding::button[1]</value>
      <webElementGuid>3bd19a65-0a8a-4e99-b536-38309fd3645f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تعديل خزنة'])[1]/preceding::button[2]</value>
      <webElementGuid>03e18f80-67e7-4b4d-ae71-873319ed8a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='حفظ']/parent::*</value>
      <webElementGuid>6252af10-52da-4cc8-a00f-e4a61264f72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>1c798323-3d3a-4aa2-bd45-a2283c9e5c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'save_print' and (text() = 'حفظ
                        ' or . = 'حفظ
                        ')]</value>
      <webElementGuid>dcf9273e-93ca-41ef-abbc-6e66c04b508d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
