<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__name_en</name>
   <tag></tag>
   <elementGuidId>7c0651b7-35a6-439a-947c-686df4c27318</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name_en</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='name_en']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11eca06b-6747-47eb-b874-cc6fe1258719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name_en</value>
      <webElementGuid>9ca5014a-947d-4878-9575-f2b6f21e6653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8aa5a005-b159-4955-a6ab-77813d8f81e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54a83adf-194b-4b0f-b7bb-2f89cf04f469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name_en</value>
      <webElementGuid>bd52cb31-1dee-486f-b7e4-8aad25b5b6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name_en&quot;)</value>
      <webElementGuid>d3c1c3c1-304f-41f4-be7c-acb7bd29b736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='name_en']</value>
      <webElementGuid>083cb6fa-8432-4415-825a-191e98abc038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add_from']/div[2]/div/input</value>
      <webElementGuid>8d3b8ed5-f7e4-4490-8b0f-908926905084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>072b5321-cbbe-4464-9f90-68562397a3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'name_en' and @type = 'text' and @name = 'name_en']</value>
      <webElementGuid>a0222c4d-ca24-4640-8b0d-76eb3102e001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
