<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__record_number</name>
   <tag></tag>
   <elementGuidId>32570af0-b97d-4bd8-9373-0666b209e32a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#record_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='record_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d74ff515-6e9b-4d9a-baee-92a54704541f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>record_number</value>
      <webElementGuid>7806a582-7555-470e-8512-1f8b0b1bfdd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>record_number</value>
      <webElementGuid>0b3f553c-abcd-4c99-bb5d-703cd53f90bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>6c09fc75-c78f-4ff7-869e-b21adc6b205b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d986228-b352-48ca-bfc5-564dc3b3f364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;record_number&quot;)</value>
      <webElementGuid>7e0d6c1e-74f8-47ba-b736-ba9445a0dbcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='record_number']</value>
      <webElementGuid>2a739f54-5e83-4bd1-b860-aed03ef09448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div[9]/div/input</value>
      <webElementGuid>6a333d70-f816-4a0f-ae6e-46976b2c5a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>92eebaea-9ea6-437d-94e3-4a26233c68e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'record_number' and @name = 'record_number' and @type = 'text']</value>
      <webElementGuid>b189c323-2dfc-4a72-8800-87ec9ebe2899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
