<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__activity</name>
   <tag></tag>
   <elementGuidId>0195468f-b2ff-4b8f-8369-6b08255fa1c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#activity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='activity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7e878ff-d24f-4ff5-9207-83af3cc5462a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>activity</value>
      <webElementGuid>42bac572-474f-44f6-a4b2-1a948ab537b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>activity</value>
      <webElementGuid>864ead94-9e5b-40f2-8813-fc36b9f038e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>61587acd-cd0c-41a3-b641-aaa5dd156ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a19e11f-cbe5-465f-ab9f-bafa592dcb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;activity&quot;)</value>
      <webElementGuid>6b51b988-fd9c-4bc5-89a5-12fc535b7722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='activity']</value>
      <webElementGuid>8e90f0ca-3081-40ee-99c2-4139fdb0e901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div[8]/div/input</value>
      <webElementGuid>090ff6c3-11e7-4444-ae79-bc98cae72ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>c51a0fc6-9b5c-40cf-86b3-35d87833549a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'activity' and @name = 'activity' and @type = 'text']</value>
      <webElementGuid>ab174c0f-ba6e-4cf5-8956-e991327a74d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
