<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>c97d613d-b3ca-4532-9190-32366935b558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#branch_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='branch_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5c2c57a6-08f3-417a-9bea-7f3bb68839c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch_id</value>
      <webElementGuid>62a75e96-d5c2-4062-9a80-4e01218f41ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branch_id</value>
      <webElementGuid>54cb5973-26d2-4afe-adba-a50a48df2fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2d1cc189-413c-4613-83c4-245c83a4a460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                اختر فرع
                                                                                                            الريان
                                                                                                </value>
      <webElementGuid>491159ed-20a1-420a-a42c-2531a2a43ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch_id&quot;)</value>
      <webElementGuid>3f78db41-a69b-461d-b9f0-f8d4e03a109e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='branch_id']</value>
      <webElementGuid>2f296f89-dffc-4fa7-8de4-3136abdd04ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div[2]/div/select</value>
      <webElementGuid>242b1e42-7f52-4ba1-96f0-cd2bb4441ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فرع'])[1]/following::select[1]</value>
      <webElementGuid>7d5049e9-0a2a-4bb8-9453-96fb51a85fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم العميل'])[1]/following::select[1]</value>
      <webElementGuid>1fa90af8-e7d9-4343-9df1-c045cf094a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم الجوال'])[1]/preceding::select[1]</value>
      <webElementGuid>6f1438d3-b64a-4af8-90e2-97acb1a1715c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم جوال آخر'])[1]/preceding::select[1]</value>
      <webElementGuid>d4cfa484-7da8-4622-a896-fa4ec8a5d36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d5d3dfa3-5b0a-468c-b8dc-778663fc6453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'branch_id' and @name = 'branch_id' and (text() = '
                                اختر فرع
                                                                                                            الريان
                                                                                                ' or . = '
                                اختر فرع
                                                                                                            الريان
                                                                                                ')]</value>
      <webElementGuid>940a3a5d-fd9e-4f75-b238-de8ff071921f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
