<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>47960622-eb52-42a3-a2f5-2b77fc615154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='removable2']/td[10]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.add_balance.btn.btn-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c340256-6d25-4269-954c-efc9c3851ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientname</name>
      <type>Main</type>
      <value>سعفان</value>
      <webElementGuid>d3ac2115-49bf-4c03-a515-c26af890227d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>99ca3f55-2eed-427c-90da-5eee88b99783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_balance btn btn-info</value>
      <webElementGuid>4f766b1e-3239-4325-b24a-a09b3edea228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اضافة رصيد</value>
      <webElementGuid>4fe3e85b-dbf0-4f12-bfe4-949745331f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;removable2&quot;)/td[10]/button[@class=&quot;add_balance btn btn-info&quot;]</value>
      <webElementGuid>0ed9c1b7-7770-4673-8a58-6e812b3348d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='removable2']/td[10]/button</value>
      <webElementGuid>b4d03e75-eaac-4aec-8df2-6bcbd547b4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نشط'])[1]/following::button[1]</value>
      <webElementGuid>c5d3e455-596b-4004-bec1-e1bc71520bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الجبيل'])[1]/following::button[1]</value>
      <webElementGuid>75dd321e-3f1c-43a5-b89d-a174f7de00dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سحب رصيد'])[2]/preceding::button[1]</value>
      <webElementGuid>42f9022e-50ae-47fb-b773-8a982175c2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تعديل'])[1]/preceding::button[2]</value>
      <webElementGuid>6c3bb41f-f2b6-496a-8a95-e4018153a0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/button</value>
      <webElementGuid>d145549c-6135-43ee-8e98-c64fd3d1039a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'اضافة رصيد' or . = 'اضافة رصيد')]</value>
      <webElementGuid>18d97f3f-ca1b-4374-980e-47477f3fec57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
