<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>47faea5b-dc71-4720-a1bb-a0910bb6c3c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='side-menu']/li[15]/ul/li[4]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ebb220a4-b074-4e41-a06a-e13db76d3e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://albadrsupport.com/container-testing/AddContainer</value>
      <webElementGuid>8bb7bad0-72c5-47ba-a284-3daf527d3b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إضافة حاوية</value>
      <webElementGuid>d5ffba2d-7bae-4412-aa99-acb699808f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[@class=&quot;active&quot;]/ul[@class=&quot;nav nav-second-level collapse in&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;nav nav-second-level collapse in&quot;]/li[3]/a[1]</value>
      <webElementGuid>9cd0038d-0367-4a1d-9ece-505ef4740393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side-menu']/li[15]/ul/li[4]/ul/li[3]/a</value>
      <webElementGuid>7a84f8d4-3384-4830-8f68-6da2c46c956d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'إضافة حاوية')]</value>
      <webElementGuid>73f95b2b-920f-4867-89bd-a5db8d014f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اضافه احجام التصنيفات'])[1]/following::a[1]</value>
      <webElementGuid>d48965e0-f314-4ab3-85fe-94c406f2dfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اضف تصنيف'])[1]/following::a[2]</value>
      <webElementGuid>692e3627-5ced-414d-b20d-dc9cd4e22e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إضافة موظف'])[1]/preceding::a[1]</value>
      <webElementGuid>0bd2f743-6b7a-44fc-945f-46048f350d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إضافة عميل'])[1]/preceding::a[2]</value>
      <webElementGuid>0dbf5067-234b-43f0-b26d-46e560a3c3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إضافة حاوية']/parent::*</value>
      <webElementGuid>9706af72-7cca-454f-8e14-5186b01a41f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://albadrsupport.com/container-testing/AddContainer')]</value>
      <webElementGuid>d27c3591-ac7d-4163-8c7f-a803c0c745cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[3]/a</value>
      <webElementGuid>d6374e10-b5bf-4c4a-9cb8-a52c6c38b869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://albadrsupport.com/container-testing/AddContainer' and (text() = 'إضافة حاوية' or . = 'إضافة حاوية')]</value>
      <webElementGuid>abf6ab8a-3ecd-48ca-a80a-e413d0cfff29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
