<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>5a1ecc07-32f6-4bc5-a3c6-9c9063f5d059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save_print</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save_print']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5dc406b-394f-452c-8e99-45c149a54079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 btn btn-success</value>
      <webElementGuid>56966685-bf83-4c8c-9aa3-835f4a5b926b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_print</value>
      <webElementGuid>510246a0-a844-4227-bd01-473ed0e5a708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>حفظ
                    </value>
      <webElementGuid>d5dcb63d-3a21-4a03-8e5e-e37ccf586897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save_print&quot;)</value>
      <webElementGuid>1422f195-07f9-4ee8-add7-4febc14ed03f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save_print']</value>
      <webElementGuid>b6630af2-e201-4aa4-a0c0-71ff0063d2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[2]/form/div[5]/button</value>
      <webElementGuid>b36e4d46-bb7e-4d14-be57-5856a7dbc085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم الفرع'])[1]/following::button[1]</value>
      <webElementGuid>c9b171bd-e8d0-433d-a01f-786b02221ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[1]/following::button[1]</value>
      <webElementGuid>8f1f3164-daa0-4926-9861-d9dede9c8e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الحاويات'])[1]/preceding::button[1]</value>
      <webElementGuid>6f984dc2-2045-485a-af9a-b6288a6a173a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excel'])[1]/preceding::button[1]</value>
      <webElementGuid>2e2ece1e-91e7-4c9a-8fdf-64099b017571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='حفظ']/parent::*</value>
      <webElementGuid>e1fa1bc3-fb42-4cc2-a081-041038445f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>b62ac033-5fc6-45ea-9173-9be8111980b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'save_print' and (text() = 'حفظ
                    ' or . = 'حفظ
                    ')]</value>
      <webElementGuid>10d916c5-f938-4612-83ba-eddb6d9bc66d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
