<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1</name>
   <tag></tag>
   <elementGuidId>348d2f6b-5e42-4ed1-8ae2-eccefd504abf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#branch_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='branch_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a6b46c6a-f02f-405a-8997-47ec83918479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch_id</value>
      <webElementGuid>ab8ab414-e30f-4c48-9827-f145029bb8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branch_id</value>
      <webElementGuid>3172d9bc-6b22-4e4a-96ed-42a02b07d755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8098e205-aacc-4302-badd-a4163f1be884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                اختر اسم الفرع
                                                                                                            الريان
                                                                                                </value>
      <webElementGuid>aebf85b5-f0f1-4331-b1bd-a651e3084de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch_id&quot;)</value>
      <webElementGuid>e69d918d-53ee-43a3-bdc1-20ee74198643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='branch_id']</value>
      <webElementGuid>5b656006-954a-44b3-a04b-a1051e3cbb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[2]/form/div[4]/div[2]/select</value>
      <webElementGuid>d5dea21a-35ff-489e-8692-4d7df5e9cdbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم الفرع'])[1]/following::select[1]</value>
      <webElementGuid>094c3c97-5635-418c-a141-79ca8eae0bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[1]/following::select[2]</value>
      <webElementGuid>205e9257-b792-4bd5-bffb-20115aed1097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حفظ'])[1]/preceding::select[1]</value>
      <webElementGuid>aca3a7ae-e606-4839-a277-9790b9cb5235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الحاويات'])[1]/preceding::select[1]</value>
      <webElementGuid>8cfb85d5-8815-44c4-b6b5-1cf7288e972a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>7ff7d5e2-6a50-4947-813d-6d29fc9bce22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'branch_id' and @name = 'branch_id' and (text() = '
                                اختر اسم الفرع
                                                                                                            الريان
                                                                                                ' or . = '
                                اختر اسم الفرع
                                                                                                            الريان
                                                                                                ')]</value>
      <webElementGuid>4a849007-e13c-4d74-a392-552a07e98b1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
