<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>d7c18dc6-f02b-4467-a6a6-54354ea76b63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pull-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div[3]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cce5cabe-1c79-4d9d-b965-967e844817f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right</value>
      <webElementGuid>f014c681-f221-4c77-846b-1fb5ae6431ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>477ccc42-dab9-41c6-9709-54a21df33233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#myModal2</value>
      <webElementGuid>3893cb9d-8d92-49cd-b48b-1b10bee5442f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                        اضافة
                        خزنة
                    </value>
      <webElementGuid>bc2f4ef5-cfaa-4c11-a384-67ccd9ad515b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 ibox float-e-margins ibox-content text-center p-md&quot;]/div[@class=&quot;col-md-6&quot;]/a[@class=&quot;pull-right&quot;]</value>
      <webElementGuid>d4595cc6-dc00-4406-a141-b49633644bf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[3]/div/div/a</value>
      <webElementGuid>2eb27d64-6e2c-4006-bc83-aeb05732e563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حفظ'])[2]/following::a[1]</value>
      <webElementGuid>c06bc509-6b11-41ec-9aaf-5301dec168a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نشط /غير نشط'])[2]/following::a[1]</value>
      <webElementGuid>9a270765-4ceb-4591-a63e-c4c42cdce0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[1]/preceding::a[1]</value>
      <webElementGuid>77a675ca-346b-4554-bcaa-4716080ac9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاسم'])[3]/preceding::a[1]</value>
      <webElementGuid>97f3ebb2-3f2b-4adc-bafe-67456d7e86cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>43b2a58b-38b4-4bd3-bf6c-4317cf44acdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' 
                        اضافة
                        خزنة
                    ' or . = ' 
                        اضافة
                        خزنة
                    ')]</value>
      <webElementGuid>dfe74f00-5f41-4c9c-ab99-c04681bfda90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
