<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>ac37b77b-d7de-4940-81a4-25d0eee537fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='removable2']/td[11]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.withdrawal_balance.btn.btn-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a35d71d-01fa-4ff9-92d9-7e37e5125382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientbalance</name>
      <type>Main</type>
      <value>14,100.00</value>
      <webElementGuid>4138e200-ebfe-4c9f-a68a-3c2de7601c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientname</name>
      <type>Main</type>
      <value>سعفان</value>
      <webElementGuid>d2e9a75f-9675-4455-b388-b6d541032fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>672c0836-8c5f-47a0-809f-0c528cbc6bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withdrawal_balance btn btn-danger</value>
      <webElementGuid>fae43e8b-1e0f-4075-bc6d-37a417d97822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>سحب رصيد</value>
      <webElementGuid>9798d557-1e7b-4a5b-b5f1-ec14358fbce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;removable2&quot;)/td[11]/button[@class=&quot;withdrawal_balance btn btn-danger&quot;]</value>
      <webElementGuid>f7f8768b-cdcf-4644-b10c-dd71792c7a3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='removable2']/td[11]/button</value>
      <webElementGuid>0a35fe7c-7430-4257-ad34-dda154850bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اضافة رصيد'])[2]/following::button[1]</value>
      <webElementGuid>18eb5603-5743-4224-9edb-3d439f4c9144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نشط'])[1]/following::button[2]</value>
      <webElementGuid>aee68d65-c615-4a49-b5f6-7d4fe36a1169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تعديل'])[1]/preceding::button[1]</value>
      <webElementGuid>78a553d0-f85a-40c1-9305-c5af451e55f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تغيير الحالة'])[1]/preceding::button[1]</value>
      <webElementGuid>6f912529-a24d-4cbd-8764-ad9c1929fa9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/button</value>
      <webElementGuid>ef683145-4aa6-45c8-90b9-0278d170f59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'سحب رصيد' or . = 'سحب رصيد')]</value>
      <webElementGuid>8d1fe5f4-68ed-4661-a597-9cb663b208db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
