<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__balance</name>
   <tag></tag>
   <elementGuidId>5cb9202b-40ee-4c04-ae7e-27594ba13466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='withdrawal_balance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#withdrawal_balance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b53f7d0a-3935-4842-9444-da49c9d69d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdrawal_balance</value>
      <webElementGuid>5d64fd02-5c92-4ae0-b380-9527a6eb1144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>balance</value>
      <webElementGuid>572de7eb-3be1-4d5b-bb94-c08d26a943f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>46ef7011-e350-43fc-b57b-0c18c7c010ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3353f623-e37b-40cc-95c0-15bd5e1fdf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a817c21a-d240-4a83-8f50-7ec0da470416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>081c6b2e-1a88-425b-ab39-9daaac5aeed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdrawal_balance&quot;)</value>
      <webElementGuid>c8d84281-93c8-468e-958f-77c0cbbf542c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='withdrawal_balance']</value>
      <webElementGuid>188d6864-1a01-4e0c-afaa-be964e223558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='client_withdrawal_balance']/div/div/form/div/div[3]/input</value>
      <webElementGuid>99b12f58-0259-4932-a415-a2becd5947f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div/div[3]/input</value>
      <webElementGuid>427206ec-5f86-40a9-a7ba-63ed40f32076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'withdrawal_balance' and @name = 'balance' and @type = 'number']</value>
      <webElementGuid>7f2a1a67-6c75-4ae8-b1d2-58f9f20fe1c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
