<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__show_in_rubble_contract</name>
   <tag></tag>
   <elementGuidId>e23238cd-4b47-4f07-b4b1-39fba498acef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show_in_rubble_contract</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show_in_rubble_contract']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5d9666d-4a1b-432c-ac29-be867def79b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2d30f2ec-c850-4d94-844e-b36724bd1ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_in_rubble_contract</value>
      <webElementGuid>d803d03d-7d49-4dcf-a820-5f49d529294b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>show_in_rubble_contract</value>
      <webElementGuid>1983dff4-59cd-4e01-a2f6-d3a9fd6d16c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>20c17cc3-cc91-4711-b9ad-a2a82ef74902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_in_rubble_contract&quot;)</value>
      <webElementGuid>25cc55f8-bc95-4355-8ce7-3914b5b6cac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show_in_rubble_contract']</value>
      <webElementGuid>a30f4fc4-be54-4413-87a6-3e613e96512b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add_trainer']/div[4]/input</value>
      <webElementGuid>5094ffdd-e864-4295-9e0c-8cfcf4ae25a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>56246236-d7be-432c-a331-ca582bae9ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'show_in_rubble_contract' and @name = 'show_in_rubble_contract']</value>
      <webElementGuid>8906e944-e674-4f7b-9104-0b888b9af621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
