<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__measure_unit</name>
   <tag></tag>
   <elementGuidId>d1993d36-b195-4f51-aba6-30b11dcd3ec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#measure_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='measure_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35fe26be-4ea5-4c64-9644-0618711804d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>measure_unit</value>
      <webElementGuid>3cbca5f7-8144-46d2-9d0a-e68ecb36bed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>measure_unit</value>
      <webElementGuid>6254dbaf-4ac6-4f75-a18f-4135f0522993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6677c40d-6a23-4857-a75e-c3c89e02a8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67499544-a5bc-4555-b042-304899921d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;measure_unit&quot;)</value>
      <webElementGuid>d520fc71-3b48-42a7-a200-60659de6370c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='measure_unit']</value>
      <webElementGuid>93ad263d-9fdc-4f4d-baad-07e5b11071d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[2]/form/div[2]/div/input</value>
      <webElementGuid>7009372e-1192-4eb0-afa5-34f99e70095f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>cfef94d9-43cf-4bcd-9a47-7713603ea775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'measure_unit' and @name = 'measure_unit' and @type = 'text']</value>
      <webElementGuid>faff337a-8d72-4b8c-ad18-563d2f3e4d2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
