<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__show_in_trash_contract</name>
   <tag></tag>
   <elementGuidId>6c452b9c-abee-4019-8dd1-c8e2fecee9b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show_in_trash_contract</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show_in_trash_contract']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d54a60c-5adb-447c-b397-e70c3edcaa8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>da3bc1fe-70ef-4987-ae41-e9c955bec1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_in_trash_contract</value>
      <webElementGuid>09a3fb74-86df-439c-97e7-5029f38b4dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>show_in_trash_contract</value>
      <webElementGuid>e481db20-beba-454f-ab4b-d83a965a3d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f86c626a-9e86-4a98-b8c6-a1fbd0681241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_in_trash_contract&quot;)</value>
      <webElementGuid>b7c6d97d-e45a-4dbb-9c42-576bbbcefab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show_in_trash_contract']</value>
      <webElementGuid>88b1d28d-6104-4668-8b6a-ccba5d72edb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add_trainer']/div[4]/input[2]</value>
      <webElementGuid>6fb22ece-42c3-4d93-9de8-3efc5fc541fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>69275ffa-e878-49ed-817e-120e6e6ed4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'show_in_trash_contract' and @name = 'show_in_trash_contract']</value>
      <webElementGuid>414d28ba-a2e5-4be9-8ac8-3cbb8274da58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
