<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__show_in_cash_rent</name>
   <tag></tag>
   <elementGuidId>a1bd8c5a-6386-4be9-867f-8df38990c02d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show_in_cash_rent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show_in_cash_rent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44e21c7f-0c32-4a6b-be43-9523d23fb088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4f85912e-bcca-4d93-a9da-e45925d32c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_in_cash_rent</value>
      <webElementGuid>4d7b0c1f-3221-4606-ab0e-addb67dc1f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>show_in_cash_rent</value>
      <webElementGuid>6eb860bc-f247-4da0-9163-63f244307a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>70e46b19-e08a-4a89-a8e8-8e87785171cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_in_cash_rent&quot;)</value>
      <webElementGuid>93098b25-feaf-4f40-9d55-774918b3b255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show_in_cash_rent']</value>
      <webElementGuid>be16529e-84bf-414c-9e9f-291f0008f89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add_trainer']/div[4]/input[3]</value>
      <webElementGuid>4fe187b6-b817-4649-9207-9ce221d75556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>8011f736-2100-462d-9b9c-e69600106af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'show_in_cash_rent' and @name = 'show_in_cash_rent']</value>
      <webElementGuid>135b49d4-4709-42d1-840f-322ed5fda4c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
