<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__addContainerSizeList</name>
   <tag></tag>
   <elementGuidId>a11f41bb-c544-4eed-9e0b-0c96dc6944ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addContainerSizeList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addContainerSizeList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8cabcd6a-ebda-4c09-ba57-823318a73641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success </value>
      <webElementGuid>e5833ff5-aef3-499c-b37a-d8c21ef1c1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addContainerSizeList</value>
      <webElementGuid>76925082-5251-478b-8aaf-84e7a913862f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addContainerSizeList&quot;)</value>
      <webElementGuid>8a2075ce-15af-447c-9c97-a9c902fa968f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addContainerSizeList']</value>
      <webElementGuid>6186170a-4c3c-4f9d-8019-b56b3f7f8d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_containers']/div[6]/a</value>
      <webElementGuid>fdb10b85-1a03-4350-b7a6-a8fb48994af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاجمالي'])[1]/following::a[1]</value>
      <webElementGuid>bf65d827-e41f-4439-b456-bd027e31ce28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='السعر'])[1]/following::a[1]</value>
      <webElementGuid>129b17d8-aa32-4d4f-bc52-d3f24e567301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='يجب الضغط على زر الاضافه للتاكيد'])[1]/preceding::a[1]</value>
      <webElementGuid>df984f0f-44fd-40e1-950f-f62cbcb7dccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الحاويات المطلوبه فى التعاقد'])[1]/preceding::a[1]</value>
      <webElementGuid>397d135a-188a-454c-b8f1-6c221ee6b7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>8a5dc6b3-cae1-4682-9311-c9e4bbcd90ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addContainerSizeList']</value>
      <webElementGuid>10aa962e-82cc-401e-8e1d-7f7b5c386db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
