<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__fa fa-plus</name>
   <tag></tag>
   <elementGuidId>76d736ac-29e1-4643-92bd-0839e5a31d30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addContainerSizeList > i.fa.fa-plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addContainerSizeList']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2af3c4f4-1bac-4d0d-9d66-e6ac2cb02915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>d2d06bef-685e-4b92-9d4a-92076519d6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addContainerSizeList&quot;)/i[@class=&quot;fa fa-plus&quot;]</value>
      <webElementGuid>c3f3c6bd-9c2d-430d-be48-c39a122d61cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='addContainerSizeList']/i</value>
      <webElementGuid>068a4e81-4a49-4321-b5fc-3a6aefda3677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/i</value>
      <webElementGuid>15c9ff8a-d4b4-49a4-bf61-c12313237da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
