<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_20  30</name>
   <tag></tag>
   <elementGuidId>ceb882ae-cd78-4278-b4a0-cfc1d78c3c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#size_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fbcba3a6-11d9-45c8-a35b-178b6bedafc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>912d1a67-d24e-44c7-9716-250887f674ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>4626b481-154d-431e-acc6-afb7b63f63a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control chosen-select size_id</value>
      <webElementGuid>a4449828-a8b6-4411-8486-9dafe56ac76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برجاء اختيار الحجم20 ياردة 30 ياردة </value>
      <webElementGuid>c6346752-7ddb-4e09-8c2a-473b5cf9afc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size_id&quot;)</value>
      <webElementGuid>8e2a9e38-9547-429a-be48-a29fc8836cb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size_id']</value>
      <webElementGuid>d4e9ab35-424d-461c-b2d8-636f18d677aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_containers']/div[2]/div/select</value>
      <webElementGuid>7fc5275b-6e6f-4232-921c-4064ba0f82d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[1]/following::select[1]</value>
      <webElementGuid>430a6023-27d4-4884-a954-a064c50fcd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[1]/following::select[2]</value>
      <webElementGuid>cc63bf5e-2a5a-4c1a-8c42-f53e161fe890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد الرحلات'])[1]/preceding::select[1]</value>
      <webElementGuid>e2f2cc04-ae18-4b36-9852-9b128d86565d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='السعر'])[1]/preceding::select[1]</value>
      <webElementGuid>50569347-47b5-4ef3-b70c-a479c6d7d5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>efbb1b7d-3315-4038-99d1-bbc76edb36d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size_id' and @name = 'size_id' and (text() = 'برجاء اختيار الحجم20 ياردة 30 ياردة ' or . = 'برجاء اختيار الحجم20 ياردة 30 ياردة ')]</value>
      <webElementGuid>a90020f2-ba07-4e1c-9310-9e2cc18c161c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
