<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>280173d2-2a41-4222-8bbb-6d81ec4b3bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='client_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>655e51ae-166a-4760-8e88-687c016a389e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker form-control</value>
      <webElementGuid>468d9627-2423-484d-a9a5-673ef57a3663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-live-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ba334a8-66b7-41e1-b881-b7a0be939529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a9526faa-14e3-4c90-a0aa-953adde2fe95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>client_id</value>
      <webElementGuid>439c7a03-d47b-4397-852e-3996bdc6acab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client_id</value>
      <webElementGuid>748dbeb3-96e8-4239-8242-c86a7f39e258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>إختر من قائمة العملاء ..</value>
      <webElementGuid>a08451da-ef67-464c-9cb4-8d72d8536727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>4db83368-5b3c-4d74-bdac-20a564d0dc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إختر من قائمة العملاء ..
                                                                                    شعبان
                                                            سعفان
                                                            نعمان
                                                                        </value>
      <webElementGuid>3eb0df52-9921-46d3-9af3-817b148de5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client_id&quot;)</value>
      <webElementGuid>0ccf94f4-e1aa-4371-ab6e-4b8441598bb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client_id']</value>
      <webElementGuid>17b22c74-01a3-4e0e-880a-c5c40878410a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[2]/form/div[2]/div/div/select</value>
      <webElementGuid>d2e19925-25ce-4e64-82b7-5a82600af8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نعمان'])[1]/following::select[1]</value>
      <webElementGuid>f58b5914-c067-46d3-bf51-e28cb76f85fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سعفان'])[1]/following::select[1]</value>
      <webElementGuid>6a34d2c5-fcef-4145-8108-ca00304b7638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إضافة عميل'])[2]/preceding::select[1]</value>
      <webElementGuid>07e3ec53-de80-42a1-9ed2-fe4e481faadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الموقع'])[1]/preceding::select[1]</value>
      <webElementGuid>293eda62-e4cf-4145-9c2b-4f9fcac6e4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>68e441f7-b258-4c01-a02f-d8b88d5d0a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'client_id' and @id = 'client_id' and @title = 'إختر من قائمة العملاء ..' and (text() = 'إختر من قائمة العملاء ..
                                                                                    شعبان
                                                            سعفان
                                                            نعمان
                                                                        ' or . = 'إختر من قائمة العملاء ..
                                                                                    شعبان
                                                            سعفان
                                                            نعمان
                                                                        ')]</value>
      <webElementGuid>c0e91f45-7bd6-454d-a1c7-4be0f231b654</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
