<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_20  30_1</name>
   <tag></tag>
   <elementGuidId>8b842398-b4e2-408e-a349-ee69a7bcadf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#size_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>14427b2d-2377-4c2b-b753-3ae5a2c0b1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>451fae32-56dc-43bb-93ef-bc841a89d92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>646bb00e-04f9-4f9a-80f1-b655c185d898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control chosen-select size_id</value>
      <webElementGuid>bca1270a-6cdb-4998-b8b8-70854ff9416b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برجاء اختيار الحجم20 يارده 30 يارده </value>
      <webElementGuid>66dcf644-38ad-4b88-b2b4-a1ddc045e533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size_id&quot;)</value>
      <webElementGuid>4852afeb-35c4-4699-a3f5-6d26e198fec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size_id']</value>
      <webElementGuid>04675927-5317-46f6-bfb6-a726d9603226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_containers']/div[2]/div/select</value>
      <webElementGuid>1940fbc4-3ace-4db9-aeb5-febd561aaf74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[1]/following::select[1]</value>
      <webElementGuid>0204efc9-7638-4258-8f35-594a983241d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[1]/following::select[2]</value>
      <webElementGuid>7c17c004-511d-4eec-be33-3c09daa701a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد الرحلات'])[1]/preceding::select[1]</value>
      <webElementGuid>4bebcce7-ef09-4a90-a5c4-604d00957ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='السعر'])[1]/preceding::select[1]</value>
      <webElementGuid>05cbed27-d0db-47d3-9531-b75227d299fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>8d8a693d-8ff8-4dc7-9bb0-7493394ed48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size_id' and @name = 'size_id' and (text() = 'برجاء اختيار الحجم20 يارده 30 يارده ' or . = 'برجاء اختيار الحجم20 يارده 30 يارده ')]</value>
      <webElementGuid>822f31a6-149d-45ce-a11e-b36fe29d0211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
