<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1</name>
   <tag></tag>
   <elementGuidId>c77c8059-c80c-411c-b905-0ec9605e0d77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#classification_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='classification_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8bda3177-6b0e-496c-9856-cff6622fc1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control classification_id</value>
      <webElementGuid>35532b87-66c4-4f6e-8b4d-827e155631d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>classification_id</value>
      <webElementGuid>18868405-5ecf-413c-9509-cf0587e595c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>classification_id</value>
      <webElementGuid>08a8458c-5797-469a-bab4-162d3f2a80c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('please select classification')</value>
      <webElementGuid>8d0dae31-4407-43b7-af37-b7584432e66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>91c20337-deed-4e13-936d-54e48b1a98f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            برجاء اختر التصنيف
                                                            نفايات
                                                            انقاض
                                                    </value>
      <webElementGuid>443b8b89-0eda-4b0a-8075-fdcb5628853d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;classification_id&quot;)</value>
      <webElementGuid>6828db3b-8b84-4463-ad65-3caeefc0ff87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='classification_id']</value>
      <webElementGuid>f0171530-4c99-467b-8b8e-3a747fe8a267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_containers']/div/div/select</value>
      <webElementGuid>67ad07c1-b312-43af-a459-47112ceff47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[1]/following::select[1]</value>
      <webElementGuid>2b7c50b3-1297-4c70-993e-ca99c5b1b19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد المراحل'])[1]/following::select[1]</value>
      <webElementGuid>601f3fea-947b-44d6-84a3-393abec18956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[1]/preceding::select[1]</value>
      <webElementGuid>2e9d5cda-d38d-49c1-aa4d-9a95afa915fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد الرحلات'])[1]/preceding::select[2]</value>
      <webElementGuid>19ebbafc-ddab-472d-aeb6-28d68641af93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/select</value>
      <webElementGuid>63b95b99-ee38-4802-840b-a4915d592ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'classification_id' and @id = 'classification_id' and (text() = '
                            برجاء اختر التصنيف
                                                            نفايات
                                                            انقاض
                                                    ' or . = '
                            برجاء اختر التصنيف
                                                            نفايات
                                                            انقاض
                                                    ')]</value>
      <webElementGuid>14bd936c-c491-44fd-bcd9-dc82971e4cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
