<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>e771bd05-f191-470d-8243-88c8c6c3560a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div[3]/div/table/tbody/tr[3]/td[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4248620-6700-4a12-8035-024f127e6a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://albadrsupport.com/container-testing/editUser/3</value>
      <webElementGuid>542bda7b-8acb-4b34-822e-98139f266888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>da78b859-d185-44db-912b-bee741312766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تعديل</value>
      <webElementGuid>6dd10f84-fdbb-4e10-8667-ef6d8afde387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 ibox ibox-content&quot;]/table[@class=&quot;table table-hover table-bordered table-striped&quot;]/tbody[1]/tr[3]/td[4]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>533ee544-b82c-46d3-bf94-07707447b538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[3]/div/table/tbody/tr[3]/td[4]/a</value>
      <webElementGuid>ea6bb9e8-4ea8-455f-8ca9-5b7c4d76345a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'تعديل')])[3]</value>
      <webElementGuid>44fffe57-2175-4371-b622-781b76f689c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مدير'])[3]/following::a[1]</value>
      <webElementGuid>08ee5f8e-3914-410f-9695-2d0cea2e4bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الريان'])[4]/following::a[1]</value>
      <webElementGuid>2ac40292-191d-4636-97db-8d954444cc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حذف'])[3]/preceding::a[1]</value>
      <webElementGuid>7a258862-7f5a-481e-b041-443691efb576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الصلاحيات'])[3]/preceding::a[1]</value>
      <webElementGuid>2a5ea780-489e-442d-9df5-09688a64c957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://albadrsupport.com/container-testing/editUser/3')]</value>
      <webElementGuid>b0388897-2bc2-4923-acd0-a341e0ec8e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/a</value>
      <webElementGuid>1b30801b-cea2-4ef7-978c-57870ad07a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://albadrsupport.com/container-testing/editUser/3' and (text() = 'تعديل' or . = 'تعديل')]</value>
      <webElementGuid>7a24ac25-060f-4c59-bbf0-71a3b40894ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
