<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>7755e505-1fd3-4cf8-9a46-4e37e964be78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delete_edit_contract_ability</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='delete_edit_contract_ability']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9a059199-f27c-4893-a84e-55ff268b376c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delete_edit_contract_ability</value>
      <webElementGuid>4cdbaf60-3f76-45ac-9450-7c3a2118cdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delete_edit_contract_ability</value>
      <webElementGuid>6d89ede2-7854-419f-a0ab-c005ed4291da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control chosen-select</value>
      <webElementGuid>e96d8768-ad2c-4ec6-b726-cfd5fbeb39c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            اختر
                            يستطيع
                            لا يستطيع 
                        </value>
      <webElementGuid>d19aae1e-c11e-42a5-b3ec-4a8f90e5d47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete_edit_contract_ability&quot;)</value>
      <webElementGuid>86224966-bedb-4d82-82da-12e451c68da3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='delete_edit_contract_ability']</value>
      <webElementGuid>ef1397b2-fb28-4de8-8864-bd8ffd6880ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/form/div[7]/div/div/select</value>
      <webElementGuid>1c3e6e81-aa94-400c-b42e-9e590280fd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إمكانيه حذف و تعديل العقود'])[1]/following::select[1]</value>
      <webElementGuid>35fca09e-ed50-483a-aaff-bbe74881dbc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إظهار إجماليات التقاير'])[1]/following::select[2]</value>
      <webElementGuid>7f49a795-141f-46d8-a12d-1844a661189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الخزن'])[3]/preceding::select[1]</value>
      <webElementGuid>5f406020-f2c8-4757-8af0-80657e29ab49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='خزينة الريان النقدية'])[1]/preceding::select[1]</value>
      <webElementGuid>e5b8a882-79ab-4fa4-8a41-3bd1ae9c66b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>0c3465bb-3d8c-48da-b676-1def9ed39265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'delete_edit_contract_ability' and @name = 'delete_edit_contract_ability' and (text() = '
                            اختر
                            يستطيع
                            لا يستطيع 
                        ' or . = '
                            اختر
                            يستطيع
                            لا يستطيع 
                        ')]</value>
      <webElementGuid>80cbe1eb-d48f-47c5-a757-9e4fe09effaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
