<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__payment_method</name>
   <tag></tag>
   <elementGuidId>4d2b8b2b-3ace-4c33-9149-ddf71733a2a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_deferred']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment_deferred</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfcb3933-99d4-43de-bce7-8842cf94f84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_deferred</value>
      <webElementGuid>fcc0050f-6278-4c94-9e2a-b1487bbcf806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>e4714550-0482-411f-8897-dab77702167e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment_deferred form-control</value>
      <webElementGuid>c6141609-7022-434a-bc1b-6e963a43983a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3d28a881-c0ad-4f05-93b0-1fa88b659693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>deferred</value>
      <webElementGuid>31e8545c-5417-4e88-9028-5c67485ce633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_deferred&quot;)</value>
      <webElementGuid>bafcda7b-9969-4133-87a5-d7d0ee961a61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_deferred']</value>
      <webElementGuid>bf696d89-ed8d-45c9-9ad7-7b294f0843bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-cash']/div[8]/div[6]/div/div[2]/input</value>
      <webElementGuid>ce7be1a7-72c9-4ac7-932d-80a1569d87cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/input</value>
      <webElementGuid>35226536-b197-49b0-94ed-c586036a4389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_deferred' and @name = 'payment_method' and @type = 'radio']</value>
      <webElementGuid>9755524a-ed22-49ca-b5a7-9ce339c4e6cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
