<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__from_date</name>
   <tag></tag>
   <elementGuidId>323a8912-4817-40b2-90b1-6c14bbcf2b68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from-date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#from-date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb0dfab3-54cf-4d66-a4a8-29dddb6cdf4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0a259b1-feb1-446a-914f-68ccde64a426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control picker is-calendarsPicker</value>
      <webElementGuid>7f81d584-3783-42a7-8654-bfe3cd3e553d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from-date</value>
      <webElementGuid>092bf005-e913-42d5-8c43-719d174e15c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>from_date</value>
      <webElementGuid>516275c9-fca9-4847-a729-49f16e5c06af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from-date&quot;)</value>
      <webElementGuid>d0995710-0056-4435-9c37-9be3d7d9fde1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from-date']</value>
      <webElementGuid>e709f507-ca68-4d48-9727-5d868ec99470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='rent-duration']/div/div/div/div/input)[2]</value>
      <webElementGuid>e01b4e50-fc98-45b1-a6d4-aa6c1296bae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/div/div/div/input</value>
      <webElementGuid>62f100b9-9275-403a-b907-f87eccb725af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'from-date' and @name = 'from_date']</value>
      <webElementGuid>30148eba-665d-41fc-9dcc-e91f3f76ea86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
