<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_20  30</name>
   <tag></tag>
   <elementGuidId>7763a3d9-2b83-4157-9eb1-7495d841d513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size_id2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#size_id2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>18abf85b-6dfa-4dc3-bdd5-3337c19de3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size_id2</value>
      <webElementGuid>0a7c2c57-5e42-40ce-b472-1ca08e9c2b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>be161d5d-a7b1-489a-afda-f254594c55da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control chosen-select size_id</value>
      <webElementGuid>1259d60f-4a32-4773-8809-8e8e16a3f5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برجاء اختيار الحجم20 ياردة 30 ياردة </value>
      <webElementGuid>45e8ccf0-99df-4cd9-87e9-b9fc8141bb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size_id2&quot;)</value>
      <webElementGuid>e2773b13-bc17-4d7d-8f94-dbd83ddafbf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size_id2']</value>
      <webElementGuid>62192f93-a309-4f06-9bc2-25e798d0b0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-cash']/div[3]/div/select</value>
      <webElementGuid>0a388fd5-ef91-4bde-929a-0c5524ad7189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[2]/following::select[1]</value>
      <webElementGuid>f18b38f3-e7ce-4dd7-a252-20974c5950dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[2]/following::select[2]</value>
      <webElementGuid>14f3a8bf-2075-4ca6-8750-8ff1d324a464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم الحاوية'])[2]/preceding::select[1]</value>
      <webElementGuid>05111163-0f9b-45c4-a063-b35a4a9829c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم العميل'])[1]/preceding::select[2]</value>
      <webElementGuid>23ee12a5-8f27-4ba0-a6fd-c409f8b7caa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div[3]/div/select</value>
      <webElementGuid>b96e2032-7060-422c-9afc-cb782c4dfb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size_id2' and @name = 'size_id' and (text() = 'برجاء اختيار الحجم20 ياردة 30 ياردة ' or . = 'برجاء اختيار الحجم20 ياردة 30 ياردة ')]</value>
      <webElementGuid>5676218a-be31-4db5-866e-02e2dc963689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
