<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>98a0343e-1989-4bfc-a997-dc729c0baaf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='side-menu']/li[11]/ul/li[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d794f515-2c18-4c32-ab7e-be62313b9a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-label</value>
      <webElementGuid>2a4a23bc-08d9-4e94-94b3-0e5ee7293981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تقارير العميل</value>
      <webElementGuid>00a012fd-4f76-4b3c-8cde-802c4bf69414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[@class=&quot;active&quot;]/ul[@class=&quot;nav nav-second-level collapse in&quot;]/li[@class=&quot;&quot;]/a[1]/span[@class=&quot;nav-label&quot;]</value>
      <webElementGuid>adb3f7a6-cbe1-4136-b2b1-e1b19a581afa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side-menu']/li[11]/ul/li[3]/a/span</value>
      <webElementGuid>e126479d-f4a8-4c91-b024-5de8a7eff7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تقرير الاجماليات اليوميه'])[1]/following::span[1]</value>
      <webElementGuid>d900148a-8c96-45ee-931c-33b88bba4789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التقرير العام'])[1]/following::span[1]</value>
      <webElementGuid>4611d113-d2da-4f6d-b503-00b35547e92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تقرير حساب نقلات العميل'])[1]/preceding::span[2]</value>
      <webElementGuid>31dbcf93-6f81-4ffc-91e9-f2a8dbfa3d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تقرير مديونية عميل'])[1]/preceding::span[2]</value>
      <webElementGuid>4e7b7ccf-961c-4517-9696-4a7665937f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='تقارير العميل']/parent::*</value>
      <webElementGuid>921728df-64a2-4338-a8a8-f54ec9aa493a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/ul/li[3]/a/span</value>
      <webElementGuid>dae89bb7-c7e5-4316-8df3-38f018a54315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'تقارير العميل' or . = 'تقارير العميل')]</value>
      <webElementGuid>6743525b-362f-4e5a-9800-0bc5faf5b932</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
