<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>9b1aed6f-94b5-444a-b2c8-61546cddc5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.block.full-width.m-b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eaf062f6-62ae-40d2-95e6-29d3ae8126e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>34fd99c5-add1-454a-bbde-2c9ea093dfbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn  block full-width m-b</value>
      <webElementGuid>6df2b55c-c223-4467-9205-9c2d35b2f234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    دخول
                </value>
      <webElementGuid>758b0ece-d367-452f-8ccc-d09c11b2372c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[@class=&quot;py-4&quot;]/div[@class=&quot;middle-box text-center loginscreen animated fadeInDown&quot;]/div[1]/form[@class=&quot;m-t&quot;]/button[@class=&quot;btn  block full-width m-b&quot;]</value>
      <webElementGuid>3d76b614-d55c-488e-83d0-138b42ccc438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>d2734fe0-120a-49d2-8841-83ffd65d5e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/div/form/button</value>
      <webElementGuid>45a81384-908d-424b-a48c-4090be2733dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='كلمة السر'])[1]/following::button[1]</value>
      <webElementGuid>44b98bba-482e-4e8c-b54b-79bfe8ed8668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم المستخدم'])[1]/following::button[1]</value>
      <webElementGuid>02366076-44a6-42ee-b529-2ec0cbf40827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جميع الحقوق محفوظة © 2023'])[1]/preceding::button[1]</value>
      <webElementGuid>e4ee11c3-b53c-4e73-9a88-69ff3b8e2de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='دخول']/parent::*</value>
      <webElementGuid>464de3bf-2582-48d5-b279-dc75fbe23d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>47117339-5220-4016-a5d2-f81cc45d0c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                    دخول
                ' or . = '
                    دخول
                ')]</value>
      <webElementGuid>79c781f2-8317-42d8-84be-51a7f39aa69e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
