<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__name_en</name>
   <tag></tag>
   <elementGuidId>d839b549-71e2-4e7d-a733-6795de83e332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name_en</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='name_en']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f7590c8-89db-478f-a598-2b855e673d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name_en</value>
      <webElementGuid>d83f6b6c-8b33-4807-8780-f82e08de9fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>513ccd39-c10a-4a1e-8537-b9dd00b3bfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90d122d7-80d2-46fc-ad93-39c6fa3010be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name_en</value>
      <webElementGuid>20b37d09-e1e6-4eba-8bfb-4be43d7ac47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name_en&quot;)</value>
      <webElementGuid>12e8450a-8289-4061-bbb0-0fbaa09ec563</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='name_en']</value>
      <webElementGuid>4cffc2c3-e66d-4b43-aad7-786ca910ad73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add_from']/div[2]/div/input</value>
      <webElementGuid>7457e40b-e78f-4375-96fb-09a98a13037b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>1b47ab4e-ba09-4913-bccc-55452d5a8396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'name_en' and @type = 'text' and @name = 'name_en']</value>
      <webElementGuid>295c2cbf-0044-457a-9f69-49ba9aaf2bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
