<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>153ead76-4145-48c4-b5d9-f61d8d7a1be0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save_print</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save_print']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0849323-abc5-49a7-9e47-91cec748c133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 btn btn-success</value>
      <webElementGuid>1925f1ba-4c8e-445c-845b-9363efddd02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>afc2edf4-be8b-4fdd-beb2-789c85035168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_print</value>
      <webElementGuid>986552f0-8677-4b25-91c4-38aa9e1c58eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>حفظ
                </value>
      <webElementGuid>16b67682-ac5b-416a-b230-55e23cf66346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save_print&quot;)</value>
      <webElementGuid>14febe3c-fd59-48c0-a3ca-988b755fedde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save_print']</value>
      <webElementGuid>ef97d38c-86a5-4cdf-934c-02632344f0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[2]/form/div[14]/button</value>
      <webElementGuid>d9aac844-a7da-44fb-8ab5-40e3502e2801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ملاحظات'])[1]/following::button[1]</value>
      <webElementGuid>26ea975a-9049-460e-8e98-babffc9726ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إنتهاء كارت التشغيل'])[1]/following::button[1]</value>
      <webElementGuid>c225818d-ba8c-4440-8a0b-f392e37c3588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم السيارة'])[2]/preceding::button[1]</value>
      <webElementGuid>2d04a14c-1589-411a-8fc0-9b43a4bcd74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فرع'])[2]/preceding::button[1]</value>
      <webElementGuid>2f7c38d5-60d0-4867-866f-9a5fd1d22101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='حفظ']/parent::*</value>
      <webElementGuid>e357f986-d505-47a6-9b6d-217c69df17a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d31879d4-93bc-4988-9d47-c5365b7116da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'save_print' and (text() = 'حفظ
                ' or . = 'حفظ
                ')]</value>
      <webElementGuid>6023545a-38c4-4689-9075-6923d92d2e23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
