<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__read_now</name>
   <tag></tag>
   <elementGuidId>c0271425-0665-460a-8ad9-9f757714ab53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#read_now</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='read_now']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f3fa8c0-d026-4fe1-a78d-8792b01db665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>read_now</value>
      <webElementGuid>5545578b-6dbe-4a70-aa6a-36813d1d83d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>read_now</value>
      <webElementGuid>e0656ab4-cb4a-4acd-a613-3ac667b96e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b6511f2c-8132-45ab-8212-10116aa18023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5fcf1512-b8f0-4829-8c55-99107d13f9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;read_now&quot;)</value>
      <webElementGuid>5e056ba8-8ded-4691-aee0-25bcc1022d1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='read_now']</value>
      <webElementGuid>8299d95c-546e-41ce-8ff4-4b3f1511dcdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[2]/form/div[5]/div/input</value>
      <webElementGuid>5b1b63c3-b9d9-4aa6-aad5-dfdfbeeafcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>4c769dac-655d-42a6-afef-c995eae58df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'read_now' and @name = 'read_now' and @type = 'number']</value>
      <webElementGuid>a57eeaed-f7f1-4407-ad34-9c18b53cb01c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
