<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1</name>
   <tag></tag>
   <elementGuidId>aba6e45b-8dda-4ff8-94c1-088c4c926fd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#branch_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='branch_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bc202d65-bcc8-4266-89c7-5d982894b267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch_id</value>
      <webElementGuid>51aec932-0dcf-4f7b-b5c7-3965202a2eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branch_id</value>
      <webElementGuid>5ff37196-4ebd-4555-aba3-64dc726cdcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>56065bec-0329-49ed-880c-6f41aa7f7a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('please select Branch')</value>
      <webElementGuid>59990d67-9e28-4c9a-a569-c2be6cf064b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>2e9e7ad9-54d6-419f-b646-0f5f1b3fdfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            اختر فرع
                                                                                                الريان
                                                                                    </value>
      <webElementGuid>7e47da68-704d-423b-8b2a-b7cd9b00f7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch_id&quot;)</value>
      <webElementGuid>40ce2189-4f61-4972-90f2-b9bc5bab777a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='branch_id']</value>
      <webElementGuid>c92c4cfa-45f5-4dd5-a528-65edc5f51ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[2]/form/div[3]/div/select</value>
      <webElementGuid>7a9a7d6c-65fb-4f70-8975-bb885e6eb375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فرع'])[1]/following::select[1]</value>
      <webElementGuid>c145832f-e996-4a21-bd35-8d694e5c3a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='السائق'])[1]/following::select[2]</value>
      <webElementGuid>001c16e4-beca-473f-8189-04aa438b7913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تبديل القماشات'])[1]/preceding::select[1]</value>
      <webElementGuid>f5d10ffe-0348-4250-ad7a-6f044555492e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='القراءة الحالية'])[1]/preceding::select[1]</value>
      <webElementGuid>dce3a535-65b6-434c-bb2a-cc54c9da8e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>b7de56d9-3446-4140-8c76-ba364ee80f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'branch_id' and @name = 'branch_id' and (text() = '
                            اختر فرع
                                                                                                الريان
                                                                                    ' or . = '
                            اختر فرع
                                                                                                الريان
                                                                                    ')]</value>
      <webElementGuid>806aae59-27ea-4f31-837b-81146a89f62d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
