<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>beef6447-057b-4615-bb82-6a4851229c44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add_item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='add_item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>029aab8c-4c3a-462a-a04d-31a3281d1236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_item</value>
      <webElementGuid>f6b9d506-81af-4327-b2f5-b77ad6e2f9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>76179578-bcb8-4ed4-9989-a723eb9db1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>93e0ae1d-517d-4b94-91bc-643ef28a9491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اضف</value>
      <webElementGuid>5076fab1-7435-445e-bfa1-ca6f550059ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/form[1]/div[@class=&quot;ibox-title ibox-content&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row m-b-md&quot;]/div[@class=&quot;col-md-2&quot;]/a[@id=&quot;add_item&quot;]</value>
      <webElementGuid>1dff335e-192e-4143-bcc7-619b1576e509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='add_item']</value>
      <webElementGuid>56a6be41-9af1-431b-9e65-88914382bf94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div/div[2]/div[3]/a</value>
      <webElementGuid>7144c9a5-9c1b-4699-a910-3f55f3e995e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'اضف')])[2]</value>
      <webElementGuid>29eb3044-ffb5-4215-8b2a-57d2cc724d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الكمية'])[1]/following::a[1]</value>
      <webElementGuid>8112187c-fb40-430b-8ed4-266c9c6ee9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاصناف'])[2]/following::a[1]</value>
      <webElementGuid>ff70e5fb-2d43-47af-9c42-30b56364136d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[1]/preceding::a[1]</value>
      <webElementGuid>58acb495-2f54-4ec1-b722-f524f24f960f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الصنف'])[1]/preceding::a[1]</value>
      <webElementGuid>08f21149-a6c4-4bfe-8abd-220e8a023f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='اضف']/parent::*</value>
      <webElementGuid>09fa248a-623e-496d-834f-6d39ea7d4f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>9eb8f59f-1e7f-4bc4-9d8c-b705c5b46528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>5df1b997-6501-49b8-8186-e750a365c7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'add_item' and @href = 'javascript:void(0)' and (text() = 'اضف' or . = 'اضف')]</value>
      <webElementGuid>9f4d6457-9bb4-4113-a314-01a88ee137d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
