<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1</name>
   <tag></tag>
   <elementGuidId>eff68a16-9f5b-40d1-a605-e652c87eafa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employee_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='employee_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d5eef8c0-f211-4ee4-b78c-777ee247ee73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>15072650-236e-4172-ae95-8eb62f1c6217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employee_id</value>
      <webElementGuid>e8120776-cf12-4411-b80f-c6e071ed4b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employee_id</value>
      <webElementGuid>3190081f-6a40-46b9-823a-7e83b78f7417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 اختر الموظف 
                                                                    مؤمن
                                                                    سعيد
                                                                    ماجد
                                                                    رأفت
                                                            </value>
      <webElementGuid>b8d3421a-291b-4db6-b607-05c7a4b23b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employee_id&quot;)</value>
      <webElementGuid>4dc51679-17fa-413a-a1b9-ac25c32170fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='employee_id']</value>
      <webElementGuid>d1bb1317-c9ef-4476-adfb-df1bb2481725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div/div/div[4]/div/select</value>
      <webElementGuid>3e92a164-f674-46ff-83f6-327fd0297235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الموظف'])[1]/following::select[1]</value>
      <webElementGuid>6c3861e2-e833-4dfb-afa7-656922eed976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='شاحنه'])[1]/following::select[2]</value>
      <webElementGuid>13b43f92-2b8e-4d83-a847-eb17aae9495c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاصناف'])[2]/preceding::select[1]</value>
      <webElementGuid>87b1c0d1-2451-4171-a6fd-3b9f58cfa1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الكمية'])[1]/preceding::select[2]</value>
      <webElementGuid>697a4573-3201-4739-b41d-d3122ab1601a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>dfb15555-2127-482c-87a2-081d92ae12b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'employee_id' and @id = 'employee_id' and (text() = '
                                 اختر الموظف 
                                                                    مؤمن
                                                                    سعيد
                                                                    ماجد
                                                                    رأفت
                                                            ' or . = '
                                 اختر الموظف 
                                                                    مؤمن
                                                                    سعيد
                                                                    ماجد
                                                                    رأفت
                                                            ')]</value>
      <webElementGuid>a67297ac-7881-4833-a3f0-50c90bf62f5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
