<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1_2</name>
   <tag></tag>
   <elementGuidId>41568018-f36f-425f-95ae-2066ed9a473c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='item_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f7986ad7-9a5e-4577-a288-62d79e88b590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f674b9dc-adcf-43a1-a6f7-145e7f020a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_id</value>
      <webElementGuid>5e05fc57-f817-412a-853f-b7ae8711ff29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item_id</value>
      <webElementGuid>296b1a89-cf66-456e-a2c9-33072797b283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اختر الصنفقماشة فرامل كبيرةغطاء سائق شتوىقماشة فرامل صغيرةغطاء سائق صيفى</value>
      <webElementGuid>6034adf2-44d4-490e-8eee-3f5d2b2235de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_id&quot;)</value>
      <webElementGuid>789eb6d7-8681-44b1-bcd3-4d1346e7e57e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='item_id']</value>
      <webElementGuid>562aa538-e95f-4039-b4e9-c2ecd6286434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div/div[2]/div/select</value>
      <webElementGuid>8a8f0f54-ed16-400e-95f9-d2acdc5764a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاصناف'])[2]/following::select[1]</value>
      <webElementGuid>11927662-6514-4a05-b8fa-76793eec345d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الموظف'])[1]/following::select[2]</value>
      <webElementGuid>eb2c970f-4d3c-4a76-a194-7d1e5a1d639b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الكمية'])[1]/preceding::select[1]</value>
      <webElementGuid>ddfb869f-4322-4ce3-94c4-79cf205adef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اضف'])[1]/preceding::select[1]</value>
      <webElementGuid>152f2da2-e85e-4da9-8d79-8f7e8e18dd07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>6a0f2fd8-7db6-4aea-bff5-deff35f19fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'item_id' and @id = 'item_id' and (text() = 'اختر الصنفقماشة فرامل كبيرةغطاء سائق شتوىقماشة فرامل صغيرةغطاء سائق صيفى' or . = 'اختر الصنفقماشة فرامل كبيرةغطاء سائق شتوىقماشة فرامل صغيرةغطاء سائق صيفى')]</value>
      <webElementGuid>e08d9220-d045-480c-9b81-527c14c3ca1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
