<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5</name>
   <tag></tag>
   <elementGuidId>f4644706-2448-4898-b819-b74660901520</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'5')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c1d2526-2301-4e98-8b44-6bfdd8ff0cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>c9225213-452e-41c2-a0e5-5f8db362f56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jd2460008.5 calendars-weekend calendars-today calendars-highlight</value>
      <webElementGuid>a7081a71-3fac-49d1-9894-741578f9be4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>اختر Sun, Mar 5</value>
      <webElementGuid>7ff2913f-9cd1-4c10-b99a-e91b5ea6ee43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>38eb30d7-f686-4a65-9e34-813f97b46d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done&quot;]/div[@class=&quot;calendars-popup&quot;]/div[@class=&quot;calendars calendars-rtl&quot;]/div[@class=&quot;calendars-month-row&quot;]/div[@class=&quot;calendars-month&quot;]/table[1]/tbody[1]/tr[2]/td[1]/a[@class=&quot;jd2460008.5 calendars-weekend calendars-today calendars-highlight&quot;]</value>
      <webElementGuid>f46fda75-2a4f-43f6-ad03-e0becd600841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'5')]</value>
      <webElementGuid>16385123-e9ac-43cc-8df0-51725789ffbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[5]</value>
      <webElementGuid>c9f451b6-180e-4797-9411-6fc824f9539a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::a[5]</value>
      <webElementGuid>39ffc980-9d3a-4896-8978-26397299a0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مسح'])[1]/preceding::a[27]</value>
      <webElementGuid>d089ff95-a5c6-415c-b3b3-bdf8a3b007fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إغلاق'])[1]/preceding::a[28]</value>
      <webElementGuid>8c4efb31-b62b-41ed-820c-7e9fdc8d1ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5']/parent::*</value>
      <webElementGuid>501afad8-b57e-47ec-b4ba-9a4e47fa437a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[9]</value>
      <webElementGuid>9c8fc8fb-9c9b-40a5-9a34-97ada9c6f7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[2]/td/a</value>
      <webElementGuid>fd61a033-3570-43b9-b551-cc5bb37c7e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @title = 'اختر Sun, Mar 5' and (text() = '5' or . = '5')]</value>
      <webElementGuid>41e6fdb8-e1a4-45d0-aeb2-3bd185a8e5bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
