<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__addContainerSizeList</name>
   <tag></tag>
   <elementGuidId>07e98456-f9e2-48f0-951f-24f7e8a3ee32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addContainerSizeList']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addContainerSizeList</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>46de0496-69ae-4076-917b-7d5f604f35ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success </value>
      <webElementGuid>fc78ebad-4616-49aa-bea2-ee7a35eaf063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addContainerSizeList</value>
      <webElementGuid>84eafb83-34da-42f9-82da-6a5d8c37e7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addContainerSizeList&quot;)</value>
      <webElementGuid>537c2b92-ffdc-4574-b82e-ee844d4155c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addContainerSizeList']</value>
      <webElementGuid>6f4844c0-b178-43ae-ae4d-7adf0c80774e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_containers']/div[6]/a</value>
      <webElementGuid>887035fd-3df5-4a97-9867-900ca8c488cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاجمالي'])[1]/following::a[1]</value>
      <webElementGuid>fa0baea7-b314-4390-915e-2b98e2e3e881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='السعر'])[1]/following::a[1]</value>
      <webElementGuid>18ee8708-cedf-4109-94a5-0bf007142f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='يجب الضغط على زر الاضافه للتاكيد'])[1]/preceding::a[1]</value>
      <webElementGuid>1bbf8ffb-0bab-4ef0-9cc9-db3ce350141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الحاويات المطلوبه فى التعاقد'])[1]/preceding::a[1]</value>
      <webElementGuid>b198f1f3-2ae5-4054-8b3c-40778250f0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>fc901ce7-5953-407b-a303-66e9ccefc1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addContainerSizeList']</value>
      <webElementGuid>150bd6af-4d48-485e-812d-a08597148de1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
