<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1</name>
   <tag></tag>
   <elementGuidId>5720d46f-2796-401c-b135-de255beb5284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='classification_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#classification_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b948c74f-fdc0-45ec-8d95-3e6d32b2df9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control classification_id</value>
      <webElementGuid>41bc97fa-642b-49fa-a0b3-0f9db31c202a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>classification_id</value>
      <webElementGuid>6875de73-dee5-48d6-9efa-3151569f16f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>classification_id</value>
      <webElementGuid>bff0cb8f-7223-44e2-9df0-317913f94826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('please select classification')</value>
      <webElementGuid>d976cefd-6f5a-46fd-8430-9d1f56ea3344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>fc74f4c8-c914-40e2-90c8-1985803b9b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            برجاء اختر التصنيف
                                                            نفايات
                                                            انقاض
                                                    </value>
      <webElementGuid>e384f73b-5d21-47a5-af1d-ad5d1c54c215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;classification_id&quot;)</value>
      <webElementGuid>59b21af8-0cab-4763-955f-06677109682d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='classification_id']</value>
      <webElementGuid>9da94cee-1803-4f2c-8ca0-13f2fb0fcc36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_containers']/div/div/select</value>
      <webElementGuid>7ded03a7-7bc9-4ff5-8142-8cfde7183372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[1]/following::select[1]</value>
      <webElementGuid>78c554c8-6c90-44f6-acd4-95d42fdd1f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد المراحل'])[1]/following::select[1]</value>
      <webElementGuid>7e8251de-bfe5-40af-8dbe-ff06bd539dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[1]/preceding::select[1]</value>
      <webElementGuid>5a18fc8c-eeab-40ae-8347-8f65b2e6a605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد الرحلات'])[1]/preceding::select[2]</value>
      <webElementGuid>993544a5-a70d-47df-a730-99b3369c750f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/select</value>
      <webElementGuid>68abc0df-27b0-4f58-857b-b8f740d2db69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'classification_id' and @id = 'classification_id' and (text() = '
                            برجاء اختر التصنيف
                                                            نفايات
                                                            انقاض
                                                    ' or . = '
                            برجاء اختر التصنيف
                                                            نفايات
                                                            انقاض
                                                    ')]</value>
      <webElementGuid>1f79a930-4b4a-42f6-b0dd-1a901ce864b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
