<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_23033 23036 23039 230310</name>
   <tag></tag>
   <elementGuidId>ba1df304-3455-4345-83c5-28e28fb4b77a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='contract_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contract_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>200d9c34-9885-4777-ae91-c4f1a0a97fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control chosen-select</value>
      <webElementGuid>5896a2b9-109f-4e5c-b5a3-a478fd86dd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contract_id</value>
      <webElementGuid>0f590b6a-57fd-45eb-9780-a4893d77da2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contract_id</value>
      <webElementGuid>b314b611-3737-4ec7-9ef5-f7ab84730867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('please select client contract number')</value>
      <webElementGuid>d783f486-42af-4ac8-8601-ca32f1bae603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>fcd02b56-b609-4ee8-8875-6349693fa7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اختر رقم العقد23033 23036 23039 230310 </value>
      <webElementGuid>a5db9673-5198-4760-a8bc-1667d4f376c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contract_id&quot;)</value>
      <webElementGuid>9460b398-b495-4cdb-b7da-9f982c890254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='contract_id']</value>
      <webElementGuid>31735433-3de3-44e6-990b-fe09db0e683f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='client_contract_number']/div/select</value>
      <webElementGuid>2ab38c8f-6062-47cd-9605-674d4fd65e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم العقد'])[1]/following::select[1]</value>
      <webElementGuid>9deeb746-1051-4743-8618-eee1211cb6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اجمالى التعاقد :undefined'])[1]/preceding::select[1]</value>
      <webElementGuid>23173f62-3127-4bb2-a020-5851e2bd145c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المدفوع:undefined'])[1]/preceding::select[1]</value>
      <webElementGuid>cbfdac35-86d6-41fa-8bfa-58255802ef5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>7bb35307-1f41-45f4-9ec2-38930415361f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'contract_id' and @name = 'contract_id' and (text() = 'اختر رقم العقد23033 23036 23039 230310 ' or . = 'اختر رقم العقد23033 23036 23039 230310 ')]</value>
      <webElementGuid>a8c34170-9621-4526-aa1f-e0ea56ac0cd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
