<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__to_date</name>
   <tag></tag>
   <elementGuidId>7bfdc050-a2fd-476f-9965-ec9d133545e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='to-date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#to-date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>399249f5-d879-46b1-9cac-36c3f715365d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>579c85a1-6965-4656-a690-9c29fd8dc17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control picker is-calendarsPicker</value>
      <webElementGuid>2630995a-a661-4dc3-81a7-6e3935063ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>to-date</value>
      <webElementGuid>ef957445-fab5-4c0c-a687-15a4186e9a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>to_date</value>
      <webElementGuid>5ac99f1a-dab9-4032-9df1-594ae5b61310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;to-date&quot;)</value>
      <webElementGuid>299c9fc1-b0a3-4837-b0af-0ed5d5bb8e77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='to-date']</value>
      <webElementGuid>1d974e18-35a2-40c8-ac1c-244ef1514ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='rent-duration']/div/div/div[2]/div/div/input)[2]</value>
      <webElementGuid>3c2b5125-fc4f-425e-b73b-420cd30971f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>89116095-faa9-4248-82ab-b88edafa5f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'to-date' and @name = 'to_date']</value>
      <webElementGuid>b8614fd6-90fa-4ae2-a070-05f13685d220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
