<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_20  30</name>
   <tag></tag>
   <elementGuidId>0f3e4671-cdcb-4dc8-995a-61a28ae656a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size_id2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#size_id2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0300df71-d551-40de-8e00-940e624cb018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size_id2</value>
      <webElementGuid>ed023df9-e48f-419a-97d9-386628624bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>602e13c9-9ead-40ed-96ba-b4eeb48b0bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control chosen-select size_id</value>
      <webElementGuid>47869657-6bf2-4c57-be0f-3a09aa542d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برجاء اختيار الحجم20 يارده 30 يارده </value>
      <webElementGuid>7457434d-9b01-4810-a04b-bbbfe0f4e5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size_id2&quot;)</value>
      <webElementGuid>eedf1cf9-4299-4e2a-b6b2-4d0eb092d03b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size_id2']</value>
      <webElementGuid>c37775dc-b5de-4e5e-a5dd-fc8d882de283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-cash']/div[3]/div/select</value>
      <webElementGuid>90788f54-bde3-43c6-bbe2-c81d0b285f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[2]/following::select[1]</value>
      <webElementGuid>3b42b336-0d86-43f6-892a-56c1437d2f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[2]/following::select[2]</value>
      <webElementGuid>8e5070e0-139a-45d4-b14a-d3fefbe649f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم الحاوية'])[2]/preceding::select[1]</value>
      <webElementGuid>f9bc0cc7-53cf-41ce-91a7-3acf6d3ad123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم العميل'])[1]/preceding::select[2]</value>
      <webElementGuid>960a29bc-78d3-434b-a772-a1830c559587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div[3]/div/select</value>
      <webElementGuid>4523a465-5023-46a4-b2c6-567d262060d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size_id2' and @name = 'size_id' and (text() = 'برجاء اختيار الحجم20 يارده 30 يارده ' or . = 'برجاء اختيار الحجم20 يارده 30 يارده ')]</value>
      <webElementGuid>a669581a-a546-47f0-b620-9a4dfcd98b51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
