<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tax_value</name>
   <tag></tag>
   <elementGuidId>37e40996-b12b-4668-a695-058725f81b9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tax_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tax_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e686577d-3cd8-417f-b99f-95a7a4ff26ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d52714c8-37a0-4490-bfc6-71390f88fe8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tax_value</value>
      <webElementGuid>e973bd17-44cb-4da2-9444-4b6d6736539d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tax_value</value>
      <webElementGuid>f349cce5-1184-4c6b-b37c-8b4a69f86bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dd088ee7-3ecd-4f01-9fef-e2cd83586a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>72371ef6-82f8-448b-9b07-c83217293f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tax_value&quot;)</value>
      <webElementGuid>e8cca927-8061-4f3d-842d-c336d8de806d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tax_value']</value>
      <webElementGuid>44ee6eeb-11cc-49f2-9d7c-ee5d6966e2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add_from']/div[4]/div/input</value>
      <webElementGuid>214c48ff-f4f0-42bf-86ed-e98553928011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>1d835f39-81c6-4f06-98d6-bfc9f7533c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'tax_value' and @id = 'tax_value']</value>
      <webElementGuid>deb8cdde-82bd-4723-b5de-d312cda8dfc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
