<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tax_name</name>
   <tag></tag>
   <elementGuidId>3912f1f6-ea48-4a8f-a046-56202390949c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tax_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tax_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c27f8d7a-1cde-49d1-af83-fdf49516ec2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tax_name</value>
      <webElementGuid>33b5e9f8-fd74-4627-afaf-6f72e9fb8e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>393f19ea-08d3-4185-b463-19384704ef82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d3f12d01-5bf4-4f55-a65f-d1aa28f138da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tax_name</value>
      <webElementGuid>e92a6aac-3f30-46dd-b253-8664473aa502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tax_name&quot;)</value>
      <webElementGuid>59213f88-5172-45da-8fb1-3b899b59f81b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tax_name']</value>
      <webElementGuid>08aee9ce-960b-4917-b32b-5b1bd3408653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add_from']/div/div/input</value>
      <webElementGuid>2053a330-bf50-46ed-8e13-4e5f6d382c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>041dbc22-6c59-44bb-8a1d-0b1afcfc5fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tax_name' and @type = 'text' and @name = 'tax_name']</value>
      <webElementGuid>a22bd228-8f72-42e1-b702-671a22a8d12c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
