<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>48291c77-f722-4efe-9c6b-c19665a2d268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tax_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tax_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c8f121cd-a0ef-4676-8696-8cd6367d1c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tax_type</value>
      <webElementGuid>86a5d27c-14a8-4827-9897-5a6a73280580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tax_type</value>
      <webElementGuid>a6504276-7e3b-42d7-b38e-cfc2ccad323a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bceb8111-a0ae-4785-ab63-cf92e6864bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            اختر
                            نسبه
                            مبلغ ثابت
                        </value>
      <webElementGuid>08b36a1c-4b75-43fe-b5ce-7b9b0c874c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tax_type&quot;)</value>
      <webElementGuid>7b5a249f-b21f-4266-98b4-296d06d1bac2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tax_type']</value>
      <webElementGuid>bb7cc22e-a308-4c0e-9ed1-c725e932fc77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add_from']/div[3]/div/select</value>
      <webElementGuid>4547d02b-176d-4e6a-9a27-256509d941f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نوع الضريبة'])[1]/following::select[1]</value>
      <webElementGuid>ae81ef4c-ef0e-4ef5-b35a-0745661767f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نشط /غير نشط'])[1]/following::select[2]</value>
      <webElementGuid>b9b7d813-3f7e-4334-8123-3618707f58f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قيمة الضريبة'])[1]/preceding::select[1]</value>
      <webElementGuid>f739710f-4952-4349-bd76-e59da21cab7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حفظ'])[1]/preceding::select[1]</value>
      <webElementGuid>e91fedb0-47d3-4007-b896-db9fbd595234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>67202cd9-7b66-4d7d-ae31-82bb7d4dac8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tax_type' and @id = 'tax_type' and (text() = '
                            اختر
                            نسبه
                            مبلغ ثابت
                        ' or . = '
                            اختر
                            نسبه
                            مبلغ ثابت
                        ')]</value>
      <webElementGuid>62e5408c-d190-46a2-b415-2ddd54f0570f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
