<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___</name>
   <tag></tag>
   <elementGuidId>964e0d4b-cfff-4652-adc0-10c0c9e6ee49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#اعدادت_المؤسسه</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='اعدادت_المؤسسه']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c47463a-9727-4b9b-8cba-ecfa976c2107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>900fc5f2-2977-4d09-a62a-799bf59eb418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>6ba9c11c-0cd1-46bb-964a-82bd62b9c6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>اعدادت_المؤسسه</value>
      <webElementGuid>96b8084d-3628-42fb-90ef-d7588a277352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;اعدادت_المؤسسه&quot;)</value>
      <webElementGuid>0a61f913-52c8-4312-8de2-6ba31320e05b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='اعدادت_المؤسسه']</value>
      <webElementGuid>f01e8b4e-ac63-4ce0-ac6b-e59955320bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div/div/div/label/input</value>
      <webElementGuid>c0991136-c1c8-430c-9cd2-9eb53c1720b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>f3f6df3e-7701-424c-9e61-bdfd9d7ab5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'اعدادت_المؤسسه']</value>
      <webElementGuid>fdc61fcc-a350-4f58-a2ec-78956533b830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
