<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6_7_8_9_10_11_12</name>
   <tag></tag>
   <elementGuidId>caabd2e3-d85a-417e-a3b7-f2efdf7b1f32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الفروع</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الفروع']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7482da66-99b7-44b6-8657-5c7ff6d2b0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>04db5503-96d3-4372-aeab-8ba3914e53b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>b4f18f88-01d2-4404-a257-9877f0825dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الفروع</value>
      <webElementGuid>994ec5ba-c223-4872-88e6-12ccef52a1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الفروع&quot;)</value>
      <webElementGuid>10748489-a2fa-4f9f-aa0f-c532daac1e49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الفروع']</value>
      <webElementGuid>c9304999-8a86-4a5d-af39-df3b7d8e7415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[23]/div/div/label/input</value>
      <webElementGuid>eb6aa551-c237-4459-a21d-f8aec1669383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/div/div/label/input</value>
      <webElementGuid>22838fa4-b215-4c39-a002-e675b5eaa002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الفروع']</value>
      <webElementGuid>e1cf950b-b8ff-4a58-adf8-caebb8637c32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
