<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6_7_8_9_10_11_12_13</name>
   <tag></tag>
   <elementGuidId>90b05069-6ab8-4216-8376-52b4f52f1335</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الفواتير</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الفواتير']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75414861-5308-4196-a5c3-26382154f2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>48e5472f-d4ff-4a84-a19f-6be615a0c90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>ac8a59da-462d-4406-9ba4-fb9f6069785b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الفواتير</value>
      <webElementGuid>4fff33a7-ae82-4208-9aa5-625c5ebe2989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الفواتير&quot;)</value>
      <webElementGuid>af537920-3e18-49ad-bd32-09c7ad94a368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الفواتير']</value>
      <webElementGuid>2f4bcd25-cdda-45ec-894b-2d390c47a682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[25]/div/div/label/input</value>
      <webElementGuid>77d0e19e-2a30-4fc8-879d-3a991ce2dfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/div/div/label/input</value>
      <webElementGuid>43b0b75e-1c4f-41c0-8981-15ff853a8212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الفواتير']</value>
      <webElementGuid>0987da2a-4e85-4549-8b98-5edbb055bf0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
