<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>7326aaa8-21e8-4870-ae1e-44802d22df8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الشاحنات</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الشاحنات']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7573cc37-7343-4e68-be10-607d4ba16336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e4c7f00d-a8e3-4346-9fcb-ccd9f4ef4180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>c39bcd2e-7b8f-48dc-bfa4-65574a947854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الشاحنات</value>
      <webElementGuid>6ac2622f-ee4e-48f2-891f-29c469f65127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الشاحنات&quot;)</value>
      <webElementGuid>634f0a5c-1977-4df7-88e3-084815bb767d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الشاحنات']</value>
      <webElementGuid>16bee615-fe50-4ecb-a8a6-4938260c995f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[17]/div/div/label/input</value>
      <webElementGuid>5ef0eb17-3da1-41df-988c-589f199b2ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/label/input</value>
      <webElementGuid>a4d4841c-0984-40a8-a02e-bbbf0d923a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الشاحنات']</value>
      <webElementGuid>11f49fb1-75b1-4f95-baa7-cddac4621095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
