<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>ac987036-642c-43b9-bbc1-640843da4cc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#التقارير</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='التقارير']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8db3c35e-e1ba-44ac-a657-9e90aee14038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c879dcc8-1279-449d-b390-17c22a87f5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>178d352e-987b-435e-9864-55375aa53c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>التقارير</value>
      <webElementGuid>0c1d02b3-d9b3-4ce2-b0f1-1afba321c9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;التقارير&quot;)</value>
      <webElementGuid>339953b6-d567-401b-8889-567edb4e49a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='التقارير']</value>
      <webElementGuid>d9daf68f-99d6-41f2-9ae9-2a2e98380ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[10]/div/div/label/input</value>
      <webElementGuid>444bae3e-bfd2-4cba-9f77-9c59f67fac93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/label/input</value>
      <webElementGuid>0ea90138-45ac-423b-940a-d16dd95281e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'التقارير']</value>
      <webElementGuid>020f4fb9-c8f2-4514-96aa-e1409e7d1666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
