<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1</name>
   <tag></tag>
   <elementGuidId>e6ed8705-4cc1-4eff-9fc8-bbefc15909ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الاعدادات</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الاعدادات']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb1576f7-c266-4835-9a96-b991745132aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>347f0374-bc67-459c-8e9b-362d88875c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>828274f8-32d3-4fef-aa15-fff4d1550d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الاعدادات</value>
      <webElementGuid>15c07f9a-ef61-43a7-8ffa-4dfb20437a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الاعدادات&quot;)</value>
      <webElementGuid>b90d8a80-fe88-44b3-af0c-2be277f9b1b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الاعدادات']</value>
      <webElementGuid>59951e9c-7658-45bc-a249-4ac68f55ddae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[4]/div/div/label/input</value>
      <webElementGuid>74e0463a-cbda-4c3d-b053-c91b69b5ee4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/label/input</value>
      <webElementGuid>3ad5ab39-c0bb-4cf9-bbaa-3b541b098261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الاعدادات']</value>
      <webElementGuid>d0c8584a-c75f-4440-a338-210a69a3f1ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
