<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6_7_8_9_10_11_12_13_14_15</name>
   <tag></tag>
   <elementGuidId>fcb1d3c2-adf2-4c97-a101-a935c33d66eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#المصروفات</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='المصروفات']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bea96fc-677c-49cd-8a27-04b9b479927f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2105f90d-8a20-40f2-b1d9-998abef29d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>38a60a15-4eea-48bc-99a0-697609a537f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>المصروفات</value>
      <webElementGuid>82aac841-9253-4e70-ab1b-aa04844e7f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;المصروفات&quot;)</value>
      <webElementGuid>fb639164-e2d4-48e8-8ca6-6474b0c2f774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='المصروفات']</value>
      <webElementGuid>be6f2381-3047-40bd-9021-34211fa7ae8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[29]/div/div/label/input</value>
      <webElementGuid>ed3d18af-470f-4538-8521-d983781b34a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/div/div/label/input</value>
      <webElementGuid>3f9321f6-bac8-4a4d-b44e-715f8c07e667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'المصروفات']</value>
      <webElementGuid>3cdf84e3-bbaa-4855-a6e9-85f3d8fc384e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
