<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19</name>
   <tag></tag>
   <elementGuidId>577d33b6-e936-4183-9df4-f487496d78ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#المخازن</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='المخازن']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09d59f06-7c69-4c78-ae7c-fca7d88a1b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>89ff29cd-3af3-4b7a-9068-fae3c554bd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>8602f996-c955-4bc3-a0d8-d26939a6f92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>المخازن</value>
      <webElementGuid>b5dba8b4-d90b-4437-9a9d-e03e41805e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;المخازن&quot;)</value>
      <webElementGuid>113f3c72-0d2e-44ea-893c-1968cb30f9a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='المخازن']</value>
      <webElementGuid>44e75d87-ffbb-42c2-95c5-75a49e21afc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[26]/div/div/label/input</value>
      <webElementGuid>62c1047a-99b4-4f94-8919-1fee2e8ff04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div/div/label/input</value>
      <webElementGuid>072e256d-ea2a-4c04-bbce-5da230bcf8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'المخازن']</value>
      <webElementGuid>797acde3-3670-41a4-ad80-2bb96fbd10ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
