<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6_7_8_9_10_11_12_13_14</name>
   <tag></tag>
   <elementGuidId>c35f7076-0f18-4c7b-8b42-2ff2b8f33d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#المستخدمين</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='المستخدمين']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9474d8c4-8752-4272-a83c-c20d0af0307c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a7c077a3-5ad6-429a-b4e6-fe9b7ec237ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>9f348072-796d-4286-bdee-f02973fe44fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>المستخدمين</value>
      <webElementGuid>0ed26ca4-dc2a-4b01-bfeb-891e7a76511a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;المستخدمين&quot;)</value>
      <webElementGuid>5bd4de98-9ef8-45b0-ade3-e60b9b4ad44b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='المستخدمين']</value>
      <webElementGuid>1ee12c37-b0e1-4e49-a64b-07dbe50d7994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[28]/div/div/label/input</value>
      <webElementGuid>329395bb-4082-45cf-860f-07bb1a6783a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/div/label/input</value>
      <webElementGuid>1444e07c-2f52-4a06-885a-524cc69eba8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'المستخدمين']</value>
      <webElementGuid>84d7fda6-83e1-4c61-8af0-821894f3ddda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
