<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input____1</name>
   <tag></tag>
   <elementGuidId>98d70b62-f8b7-4af8-a506-bb0e830c9fba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الرواتب_والسلف</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الرواتب_والسلف']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64990cb7-78b9-4b3e-8b63-df4fa6774915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>55f65618-abfa-45f8-9953-d2ed799b46da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>2c7f5236-b89b-4948-bfc6-68e4fab6832d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الرواتب_والسلف</value>
      <webElementGuid>2f09f666-fbe8-4ea0-9d2e-138ec9feb038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الرواتب_والسلف&quot;)</value>
      <webElementGuid>1918a51c-54e6-4023-ba7e-eac128b8adf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الرواتب_والسلف']</value>
      <webElementGuid>07947958-e19a-4f00-91f2-3fc7a9307b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[16]/div/div/label/input</value>
      <webElementGuid>601385f8-1f3f-4130-aef1-64a86e6fae40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/label/input</value>
      <webElementGuid>29659024-6f54-410d-8e28-45c60e6bbf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الرواتب_والسلف']</value>
      <webElementGuid>8eb96d8c-e59a-4736-b0af-30a72ed8cbfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
