<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__</name>
   <tag></tag>
   <elementGuidId>ec92fd94-fd6a-440f-b18d-f71e8f31a179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الاصناف</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الاصناف']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddfc4cf3-46aa-46b3-8e10-a456fcc7ff26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>481158f4-eec8-42c5-a361-1400fc148af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>90736e06-d423-4254-9d91-8305a7c85a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الاصناف</value>
      <webElementGuid>2b16c635-476e-438a-a55d-0059c9224db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الاصناف&quot;)</value>
      <webElementGuid>00434bc7-1f78-4fd0-ad7e-c8865194794d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الاصناف']</value>
      <webElementGuid>1054f104-025c-4452-abc6-7c93d6c52143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[2]/div/div/label/input</value>
      <webElementGuid>81e151d0-4b32-46d9-a134-d7d131246118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/input</value>
      <webElementGuid>9ef39c26-3500-4004-a61b-2f666d7fb784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الاصناف']</value>
      <webElementGuid>8f94f8b4-9011-4640-8865-d790bb2e9950</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
