<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18</name>
   <tag></tag>
   <elementGuidId>97fccbd8-0363-42b9-bb4a-457075198984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الخزن</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الخزن']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a8720aa-f53c-4ca5-9ea3-b3d4f02ad4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ae9c6a4c-118e-4e5a-b618-3692741f2224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>2d0ffac6-8e82-42a3-a926-6707c2ecab07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الخزن</value>
      <webElementGuid>3e4e0477-cd08-43b3-9f3f-0094d1c75ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الخزن&quot;)</value>
      <webElementGuid>635a0c5e-477d-4c42-8eb9-a5784119e589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الخزن']</value>
      <webElementGuid>d22dcf2a-4e57-4622-9f34-9c8b2d1f178d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[13]/div/div/label/input</value>
      <webElementGuid>784f272b-f4e5-4674-9eb1-e42e9db65e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/label/input</value>
      <webElementGuid>0b3cdcb4-ba15-4ef3-8c82-5ff0623e7b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الخزن']</value>
      <webElementGuid>a09d8084-3c70-4f53-bc1a-5ae6a0b273a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
