<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17</name>
   <tag></tag>
   <elementGuidId>0f704284-9bbc-444a-ae3c-434c7081684f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الموظفين</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الموظفين']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d00dea6-ed91-4dc2-a1a0-5f123dd65dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4c79b621-3b69-48b7-a165-0861216a20cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>1c4ad80a-7aad-454b-916d-2a1c5eb7fb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الموظفين</value>
      <webElementGuid>5b5f0ccd-ddd0-4e25-8746-e95e46d0d2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الموظفين&quot;)</value>
      <webElementGuid>b3a094d3-1664-4c6e-9ca0-d1bc33f579cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الموظفين']</value>
      <webElementGuid>18cc7988-251f-4a15-ba3c-d3ab778d2d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[32]/div/div/label/input</value>
      <webElementGuid>ddf23386-d13b-400c-af6d-41315b12a4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[32]/div/div/label/input</value>
      <webElementGuid>dfae969e-ea71-48c0-8ee7-965b579b10cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الموظفين']</value>
      <webElementGuid>ac197005-a76b-4fe2-810b-bbfba64d75fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
