<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6_7_8_9_10_11</name>
   <tag></tag>
   <elementGuidId>f18543bf-5bbc-48e4-a876-e35b082680ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#العملاء</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='العملاء']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e951cc39-86ef-43f6-89e8-a0dcd98c0bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>86c4b082-dec1-497f-a162-826a417dc320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>1fa8083d-fbb1-4ca6-b369-bf890e267851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>العملاء</value>
      <webElementGuid>9c5bb935-6e92-4e32-b2e9-ae69335e3c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;العملاء&quot;)</value>
      <webElementGuid>0d22d11d-3965-4230-a8c7-4c68744d673e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='العملاء']</value>
      <webElementGuid>349333ce-4e08-44db-8587-d839f3545beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[22]/div/div/label/input</value>
      <webElementGuid>8f262011-da59-47e8-a04b-78e1cae9e350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div/label/input</value>
      <webElementGuid>f544b15d-c307-4897-904d-aafd2cc804e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'العملاء']</value>
      <webElementGuid>2270ab2e-90a7-4e62-b4a8-a023c196d41d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
