<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4</name>
   <tag></tag>
   <elementGuidId>3e495edf-4ae1-46ef-9e6d-eeb610d7c694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#التسديدات</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='التسديدات']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66371455-026f-49ca-8208-366f7385a0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f05e52c0-8f57-4152-8d3c-8f6e6a7a2c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>9828c003-c80e-4f42-bfab-d7135ccd9fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>التسديدات</value>
      <webElementGuid>72acea66-80c6-468f-9d5a-e67caed7172f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;التسديدات&quot;)</value>
      <webElementGuid>3bd20e40-3228-44bb-a082-ecce932998f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='التسديدات']</value>
      <webElementGuid>ec06e750-fbc1-4f9f-ac4a-2de0b1ce8426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[8]/div/div/label/input</value>
      <webElementGuid>7ad9b5fd-d5ff-4c8f-94bb-e6a77161e657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/label/input</value>
      <webElementGuid>270bbc18-0e5a-4ed2-80a5-c1bd6b8dcd3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'التسديدات']</value>
      <webElementGuid>7add1c72-09f0-4dbc-b9d4-80a79a4a4e79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
