<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>6f12fd8d-6f78-4bf9-a036-15749afa2b9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#العقود</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='العقود']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0799f9aa-918a-4239-b4de-52a81497c788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9b6244f0-f80a-4859-b28e-a281f405d9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>21adabb7-6ea1-464a-981b-34cedbb3cfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>العقود</value>
      <webElementGuid>1739aca9-20f2-4849-8bee-21dc8ad6ac13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;العقود&quot;)</value>
      <webElementGuid>fd9f00da-60b3-4701-9e7e-0dac3ebdb3d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='العقود']</value>
      <webElementGuid>ba88fe59-3191-4757-8c08-bb7c30f7aef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[20]/div/div/label/input</value>
      <webElementGuid>ddea409c-14b7-493e-a629-30183689c803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/label/input</value>
      <webElementGuid>fdb0920a-76e2-4811-bb76-d31f9afc5808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'العقود']</value>
      <webElementGuid>7a6a18d3-6037-475a-a58c-960247176b08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
