<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2</name>
   <tag></tag>
   <elementGuidId>c9a83803-e8d4-4d45-bacc-0625b3f0ec67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الايجار</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الايجار']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>572c7c89-10fa-4661-b43d-17e7ca242bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f5dde524-0b3c-4945-b215-2b13bd92c439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>89d61e5b-5e28-4798-8e50-015bd4ff0af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الايجار</value>
      <webElementGuid>07227857-c1d5-4be8-97bd-6f235383f848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الايجار&quot;)</value>
      <webElementGuid>5c7d0556-0310-49e7-bbbd-f966a3f93135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الايجار']</value>
      <webElementGuid>65f72b91-e125-4fdb-be11-49d27df28503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[5]/div/div/label/input</value>
      <webElementGuid>b4fef9dc-c48e-48bc-9ef8-3b726236270b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/label/input</value>
      <webElementGuid>591ff1d8-9fae-492a-8545-9fb6e21dbccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الايجار']</value>
      <webElementGuid>40a4d300-b66e-4ba2-ae1d-8d66307bd2d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
