<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>23836066-bd7d-4b91-a52f-40876b2c9eaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الرئيسية</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الرئيسية']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0086947-da61-42af-a2b6-d7f1e6d62ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>afd93323-84a3-4842-9f02-ca6cc7099251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>283d5c62-0970-4a03-b8fe-8ef97e07201c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الرئيسية</value>
      <webElementGuid>686d5a4e-c32c-47ff-9aaf-b529d4cc161b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الرئيسية&quot;)</value>
      <webElementGuid>36f497c5-12a7-4e04-a0f9-bc3a62e85243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الرئيسية']</value>
      <webElementGuid>c111c419-f3a4-4d8f-b74d-17f26ebd17fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[14]/div/div/label/input</value>
      <webElementGuid>3f1c0ed8-8875-4308-9a28-b2fa3718347d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/label/input</value>
      <webElementGuid>8978166e-7998-433c-a2d1-f11116a4aee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الرئيسية']</value>
      <webElementGuid>3006dee4-4f4b-4264-91ec-44806d014fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
