<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input____1_2_3</name>
   <tag></tag>
   <elementGuidId>46d1c487-bc67-42ad-a1fd-ed0b52435f42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#عمليات_المصروفات</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='عمليات_المصروفات']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b86bb46-cfbf-434d-85c8-18fa07008306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d55eae53-298d-4ac5-9259-37f4db16e30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>1069694c-0d73-46e0-a1ee-1a4f520cebc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>عمليات_المصروفات</value>
      <webElementGuid>5011e24d-3860-4d8f-8f0d-20bad65a53ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;عمليات_المصروفات&quot;)</value>
      <webElementGuid>26229957-5ce3-409f-a4bc-74b0c4d1c137</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='عمليات_المصروفات']</value>
      <webElementGuid>13294cc0-957e-4dc1-a45e-6b9b2f690bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[35]/div/div/label/input</value>
      <webElementGuid>fbc1029a-ec68-4c76-a83d-b434644acc8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[35]/div/div/label/input</value>
      <webElementGuid>e482627b-c5e8-4473-85a9-c4938c117ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'عمليات_المصروفات']</value>
      <webElementGuid>623f7108-4445-422d-93a3-247916aed553</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
