<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>495f1fdf-4ba2-410d-90ac-c4075e5220b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الحاويات</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الحاويات']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97e2a00c-7a6d-416c-91e6-b22184214bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>68cf84e8-9be5-42f9-b617-aa5bdc6913bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>3c62ddf6-9839-4957-a565-6c01cedb1221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الحاويات</value>
      <webElementGuid>f6b16fe7-3f9c-4262-9106-897e62372525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الحاويات&quot;)</value>
      <webElementGuid>45ad966a-a2d1-4c9a-a5f3-0fd7cd3d1505</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الحاويات']</value>
      <webElementGuid>9195d845-fc49-4521-9687-a8e870b64b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[11]/div/div/label/input</value>
      <webElementGuid>675c5631-195c-4b28-b49f-e81f13fd16eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/label/input</value>
      <webElementGuid>b6ed2f3f-c9e0-465e-bd22-21ce44896e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الحاويات']</value>
      <webElementGuid>5366afbd-674d-4cd8-aba1-c96f842fa8db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
