<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___1_2_3</name>
   <tag></tag>
   <elementGuidId>512903ca-a5c8-4520-b639-252d44706579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#الايرادات</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='الايرادات']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5040a4de-cc1f-4525-ad73-85563bc2190d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a3dfb25f-0c85-452d-bbd6-ba44cc230b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectSameGroup</value>
      <webElementGuid>5f821445-c4cc-46df-8c8f-b414dd28594c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>الايرادات</value>
      <webElementGuid>77d72e2b-3c50-4c65-83d5-129482456695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;الايرادات&quot;)</value>
      <webElementGuid>f4e4b322-24e0-4323-a6df-a426ee79c044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='الايرادات']</value>
      <webElementGuid>041214d5-7eee-4623-9eef-bdaef69a1289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div[2]/div/div/div/div[7]/div/div/label/input</value>
      <webElementGuid>b2106ce9-4d13-4b2a-9e46-31715b8c172e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/label/input</value>
      <webElementGuid>21c173be-fe2f-4e56-b0cb-47cff156d389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'الايرادات']</value>
      <webElementGuid>62a772e3-50d0-4559-a89a-5561acf97b0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
