<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__passport_end_date</name>
   <tag></tag>
   <elementGuidId>184a690e-e64f-42f0-a1b0-e9a111a648a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passport_end_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passport_end_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82adb226-8612-4e80-906d-78b15b57f003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64992604-d75e-4897-acdb-f6ea1d85018b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control picker is-calendarsPicker</value>
      <webElementGuid>6a4966cb-0151-4b51-b6fd-3a529041687c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passport_end_date</value>
      <webElementGuid>f15c534a-7b29-4406-80ef-8986d1677993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passport_end_date</value>
      <webElementGuid>c8bcb467-e1d8-41fa-ad15-26a1cb2d09d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passport_end_date&quot;)</value>
      <webElementGuid>99ad6909-6dde-44e6-a412-ccede2a4f37f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passport_end_date']</value>
      <webElementGuid>0426799b-9afd-4091-9df5-541cc05481ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div[9]/div/div/div/input</value>
      <webElementGuid>7d77e5f6-1e6b-45eb-9773-96f546f93475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/input</value>
      <webElementGuid>28732931-e26c-441d-9bd1-becd99886c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'passport_end_date' and @name = 'passport_end_date']</value>
      <webElementGuid>fdbe277b-11bb-427a-b577-fad29719d662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
