<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__residency_end_date</name>
   <tag></tag>
   <elementGuidId>6b7ab172-01ec-445a-b8d6-bfb9b3f58aa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#residency_end_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='residency_end_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>158b0a2f-afe4-410d-869f-4100e698d97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b392741b-b590-4deb-8591-d2b5c73e3e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control picker is-calendarsPicker</value>
      <webElementGuid>ed052510-b9d0-416a-b2a7-64699a137dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>residency_end_date</value>
      <webElementGuid>97317158-202b-4dbc-b079-6135d9b25c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>residency_end_date</value>
      <webElementGuid>f60e9070-74e4-4058-8979-91376491bf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;residency_end_date&quot;)</value>
      <webElementGuid>d7c380a1-d022-4cf2-81a7-e52f8129da43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='residency_end_date']</value>
      <webElementGuid>70fb2a43-0a63-470c-b1a1-252dc90b0cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div[5]/div/div/div/input</value>
      <webElementGuid>4378ecc4-dd2b-4bad-9a26-7066b8462d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>2d7066da-c2dc-421f-8416-2db62ce821d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'residency_end_date' and @name = 'residency_end_date']</value>
      <webElementGuid>198d00c9-db7f-4128-a607-6d049f9897c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
