<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__license_end_date</name>
   <tag></tag>
   <elementGuidId>baba986a-a382-4ff1-b311-931a197c8d4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#license_end_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='license_end_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>374f4eb0-398a-41c9-b153-b344be93ac97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eccdf99c-656d-4095-8272-30d6501c2875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control picker is-calendarsPicker</value>
      <webElementGuid>4e690ca7-55a2-4680-9a86-b76f05fbdb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>license_end_date</value>
      <webElementGuid>405a344c-885c-43ac-8c98-64442f945ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>license_end_date</value>
      <webElementGuid>71826860-bac8-42fd-b73a-ab8e999e0dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;license_end_date&quot;)</value>
      <webElementGuid>f1fe2125-4a2e-4f45-b439-619f33b16287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='license_end_date']</value>
      <webElementGuid>87efd13b-26a1-459f-90c0-cb28ff6655dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div[7]/div/div/div/input</value>
      <webElementGuid>af4314a8-0612-469c-8c1a-d1af3355b1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/input</value>
      <webElementGuid>f7aabc20-fca9-43d3-9cc2-34752bf25d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'license_end_date' and @name = 'license_end_date']</value>
      <webElementGuid>2a11655a-d5c0-4fc3-bcfd-c74225995b8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
