<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__medical_insurance_end_date</name>
   <tag></tag>
   <elementGuidId>2479a4cd-c926-412e-b944-3b4b1bc51a34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#medical_insurance_end_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='medical_insurance_end_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b0334f9-b766-41db-afb4-ed68280122f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4c75ef7-510d-483d-a3c3-5c0b9d63277e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control picker is-calendarsPicker</value>
      <webElementGuid>c44d1faa-01fe-4b5b-ba95-f9fa103109fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>medical_insurance_end_date</value>
      <webElementGuid>db78276f-58f4-4b76-bef9-6cff6773fb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>medical_insurance_end_date</value>
      <webElementGuid>cb55ced6-bcfb-4fe9-82c2-662acdbaa1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medical_insurance_end_date&quot;)</value>
      <webElementGuid>bb0eca0e-d9ed-47fe-91ff-6af65fa50673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='medical_insurance_end_date']</value>
      <webElementGuid>53799c84-acf9-4b3f-b04b-b951c4acfefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div[8]/div/div/div/input</value>
      <webElementGuid>212a2c66-56d0-44d4-9991-6b03cfba74c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/input</value>
      <webElementGuid>8063ae07-b022-4197-ab6e-f954a75c5c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'medical_insurance_end_date' and @name = 'medical_insurance_end_date']</value>
      <webElementGuid>ea960575-8e00-46d3-8417-42256a8b8f7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
