<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1</name>
   <tag></tag>
   <elementGuidId>99bd7064-1619-4a35-9961-d5ced2308014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#branch_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='branch_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eb551e63-d822-4681-afa3-d68f058656df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch_id</value>
      <webElementGuid>3bf56b67-bfb5-4ace-80a3-f151abe66dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branch_id</value>
      <webElementGuid>00e058a8-8226-4e4f-ad9f-3b2d204fcec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ae71c363-da95-49dd-a695-d8f7577a342b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                اختر فرع
                                                                                                            الريان
                                                                                                </value>
      <webElementGuid>7e6d33f1-e6c9-49bd-b700-52d74f8b2f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch_id&quot;)</value>
      <webElementGuid>458eb4a6-136c-46fd-a64e-b441f0111b65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='branch_id']</value>
      <webElementGuid>d0e94f3a-75c9-499e-aba2-d171b211f43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div[3]/div/select</value>
      <webElementGuid>50edc677-ab9d-4d1f-a492-d482dc6cd6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فرع'])[1]/following::select[1]</value>
      <webElementGuid>cea87945-ccfb-4f0c-8918-9c879315922f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوظيفة'])[1]/following::select[2]</value>
      <webElementGuid>6d679a8d-16b3-4ff3-8c57-80e4917e5a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم الإقامة'])[1]/preceding::select[1]</value>
      <webElementGuid>a5ae6b9b-e799-46c4-b921-ad9338565075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تاريخ انتهاء الإقامة'])[1]/preceding::select[1]</value>
      <webElementGuid>c0ca8150-fc17-434c-9d9a-d0585b916f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>cef498c6-de1c-4d88-a56f-398cc26c76d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'branch_id' and @name = 'branch_id' and (text() = '
                                اختر فرع
                                                                                                            الريان
                                                                                                ' or . = '
                                اختر فرع
                                                                                                            الريان
                                                                                                ')]</value>
      <webElementGuid>1883a50d-43c3-4f82-9655-34285bda075d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
