<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>8c3c765b-37d5-4935-bec3-3c42273fda94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='job']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>955644a0-91d6-4880-a959-a061a40dff3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job</value>
      <webElementGuid>830fac00-db88-4245-b1f8-fdb892fe1128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job</value>
      <webElementGuid>4202d43a-8b78-4438-b0aa-bbcb513fa0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8cd907df-72db-4df2-b4d0-4f094326ab6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            اختر الوظيفة
                            المشرف
                            السائق
                        </value>
      <webElementGuid>a3ebe817-4340-448d-a184-418781b9806e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job&quot;)</value>
      <webElementGuid>a46f9b0f-69e7-49b4-98f1-d706586189a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='job']</value>
      <webElementGuid>88988c45-ce23-4adc-9c7c-f12367d929bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/form/div/div[2]/div/select</value>
      <webElementGuid>d7a1b4f4-1a46-41f0-91ae-a7279ef42ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوظيفة'])[1]/following::select[1]</value>
      <webElementGuid>7be2cc68-37e0-4ecb-8cbf-60eec955950e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم الموظف'])[1]/following::select[1]</value>
      <webElementGuid>d9eed0a8-c28c-439d-ae9e-ae3c1babf88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فرع'])[1]/preceding::select[1]</value>
      <webElementGuid>886f4047-4e45-4174-9877-218429ea11f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم الإقامة'])[1]/preceding::select[2]</value>
      <webElementGuid>61e4957e-8aa1-4f9e-af3a-183aa886a052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1f8e3c24-5bac-41e9-8b0a-f57dbc531a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'job' and @name = 'job' and (text() = '
                            اختر الوظيفة
                            المشرف
                            السائق
                        ' or . = '
                            اختر الوظيفة
                            المشرف
                            السائق
                        ')]</value>
      <webElementGuid>8b400f9d-4861-4e1a-9867-d45f9cdcf8f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
