<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__payment_method</name>
   <tag></tag>
   <elementGuidId>19ad873d-4f70-44a0-ba42-7aa4099a8a03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment_cash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_cash']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b370f1db-7512-4236-94b6-d97fa5a253c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_cash</value>
      <webElementGuid>e50ae99e-ede5-4b7b-ae5a-180a134922f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>a37c52be-65f3-4dfa-922a-006adcc49d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment_cash form-control</value>
      <webElementGuid>b053ef1c-7d12-4782-b16f-79fb97a6c74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>560572fe-38df-4f81-a3eb-5ef950ebe1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>cash</value>
      <webElementGuid>27e7ae1f-92b4-4b44-baff-be8e069221bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_cash&quot;)</value>
      <webElementGuid>2f04e7a7-f5b0-4725-a268-bfe98fcd70a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_cash']</value>
      <webElementGuid>55eab459-7448-4878-927c-baf6d57e78aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-cash']/div[8]/div[6]/div/div/input</value>
      <webElementGuid>0f328323-8ecc-4038-ae9c-645469d1cc9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>dbf42a80-1c7d-4f2f-b023-7956edbeb9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_cash' and @name = 'payment_method' and @type = 'radio']</value>
      <webElementGuid>ed95d9b2-c521-4e90-b683-4e5f7c2b2543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
