<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__client_phone</name>
   <tag></tag>
   <elementGuidId>8f8b84a6-719a-4ab2-b415-51484a548424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cd3e3f9-2573-4915-a0cd-c4e90512ce4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client_phone</value>
      <webElementGuid>b20c9130-29cc-4571-bcd1-79ff65a44f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>client_phone</value>
      <webElementGuid>c873dfbc-2282-499b-a423-bc932fc3d85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-control</value>
      <webElementGuid>421d84f5-6b86-4073-accd-94a4e510c432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d7fcb584-d2f2-41a2-add5-bff3e23f6cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('Client Phone required')</value>
      <webElementGuid>ea219444-b3dc-4ea9-94eb-c7bb2d40345b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>4d5fe20d-4bd7-4519-8d3b-7025218f87d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client_phone&quot;)</value>
      <webElementGuid>a80d6e76-d4c1-4ffb-a765-a48aef5aec1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client_phone']</value>
      <webElementGuid>b7647ca1-a988-48ec-b9d1-177cfb081008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='phone_show']/div/input</value>
      <webElementGuid>1c72b357-7428-4084-a2ca-a18c600f243d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>ddf0837f-632e-4fc9-8cf1-9188c7a2f2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client_phone' and @name = 'client_phone' and @type = 'number']</value>
      <webElementGuid>68bcbba6-42a5-48ed-bcb7-376ef5bfd857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
