<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__to_date</name>
   <tag></tag>
   <elementGuidId>14f15332-53c9-48e2-bfdb-9d4a6a370368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#to-date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='to-date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa5d772b-19da-495a-b4a2-dd8e029ade8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a22cad42-fc51-4a1e-9b54-403c0abda2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control picker is-calendarsPicker</value>
      <webElementGuid>450ab9ef-8c3c-4b0a-ab30-e7b24a347307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>to-date</value>
      <webElementGuid>a15661e2-dc99-4bd3-8807-4c69d840fe10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>to_date</value>
      <webElementGuid>91db30ee-bdac-4bf8-b5bc-9162462294fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;to-date&quot;)</value>
      <webElementGuid>3679b17f-9170-4f09-8f2e-dd55e781e934</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='to-date']</value>
      <webElementGuid>e398c14b-3ce1-426e-8327-df090cb86131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='rent-duration']/div/div/div[2]/div/div/input)[2]</value>
      <webElementGuid>0eede4a9-cc88-4692-b4c0-4ca7c7499996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>d21046f7-8cbb-42ee-a246-b31887195f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'to-date' and @name = 'to_date']</value>
      <webElementGuid>0aa664c2-fc18-4843-a23e-f5821227c141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
