<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_20  30</name>
   <tag></tag>
   <elementGuidId>dba48199-ec62-4fd3-ab78-8635b9d3f8c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#size_id2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size_id2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6dfe6f2a-bf46-47a6-bd30-8635ba82a745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size_id2</value>
      <webElementGuid>89c57b1b-f9e6-4969-8837-0fc5b06ca029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>288e496c-a686-4301-92f2-29e21a088aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control chosen-select size_id</value>
      <webElementGuid>f679ca9a-045b-4cf3-b381-477fac736e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برجاء اختيار الحجم20 يارده 30 يارده </value>
      <webElementGuid>bae6420c-3f9d-452b-baf2-7299810bda5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size_id2&quot;)</value>
      <webElementGuid>3e627f1a-fb94-431b-bcc2-baad64a5a831</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size_id2']</value>
      <webElementGuid>45fc86b1-dad2-43d9-b8bc-c5c1f27341f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-cash']/div[3]/div/select</value>
      <webElementGuid>6f789608-3a84-45d7-a4ad-3c1aef07894a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[2]/following::select[1]</value>
      <webElementGuid>1e68a835-1a41-4df8-9053-b8b6dbb15a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[2]/following::select[2]</value>
      <webElementGuid>4e58f5b7-03e0-4cc3-821a-c109b9127963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم الحاوية'])[2]/preceding::select[1]</value>
      <webElementGuid>1027b927-e334-4c26-8f1a-09176b62e629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم العميل'])[1]/preceding::select[2]</value>
      <webElementGuid>36975559-0794-488d-a47e-0d78647bb7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div[3]/div/select</value>
      <webElementGuid>7a2b04c3-6361-464d-af04-42eff9f4790b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size_id2' and @name = 'size_id' and (text() = 'برجاء اختيار الحجم20 يارده 30 يارده ' or . = 'برجاء اختيار الحجم20 يارده 30 يارده ')]</value>
      <webElementGuid>1b240b1e-06b0-4b8d-9892-c5bf5de5088d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
