<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tax_number</name>
   <tag></tag>
   <elementGuidId>8bd39640-a45d-4436-b159-35a4958cd0c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tax_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tax_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f519c90f-f7cd-46cb-97e3-3edee2131328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tax_number</value>
      <webElementGuid>15bc089b-2cf3-4349-b93e-e357abd1ecf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3ac03e0e-b602-4ac0-b884-b1acc714b592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7483a1fc-63da-4114-9b40-ee14af477219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tax_number</value>
      <webElementGuid>34c70b5d-358f-42cc-82e4-3e3ade6e5423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>25634525554</value>
      <webElementGuid>8183344b-5de8-43a3-a39f-f69f32f9a671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tax_number&quot;)</value>
      <webElementGuid>c7f093c7-0363-45e2-b26c-1e0e4df32f21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tax_number']</value>
      <webElementGuid>3bd9c980-6ead-469d-a02d-60b9835803fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/form/div[8]/div/input</value>
      <webElementGuid>6e219f72-7d39-4035-a945-164028d8a3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>d4273e3d-d3ff-4aa1-b977-843224f30b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tax_number' and @type = 'text' and @name = 'tax_number']</value>
      <webElementGuid>40992ab1-7f2d-4eca-bf51-998de3be36a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
