<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__commercial_register</name>
   <tag></tag>
   <elementGuidId>fa6ff367-4ffe-4a4e-a5ce-8f338573d677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#commercial_register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='commercial_register']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfb83e33-e1bc-4ee5-a2e5-0407f57cdee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>commercial_register</value>
      <webElementGuid>1e35244a-418c-447f-a5c0-746db8c437b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3843be16-3686-45e7-b438-e31f18dc6f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32573124-b3ff-488d-a597-c612ecefbf2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commercial_register</value>
      <webElementGuid>9defd0f5-ad9c-46f5-9b8d-393d665f8544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2126549865</value>
      <webElementGuid>9a37a698-d0d8-48f5-8524-a3f5e5776f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commercial_register&quot;)</value>
      <webElementGuid>fa3df468-2812-45b7-8a16-0b4eb468a704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='commercial_register']</value>
      <webElementGuid>a85afbc0-8cfe-4970-be81-b1e056e3b3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/form/div[9]/div/input</value>
      <webElementGuid>a7f4794c-0e51-4b58-8f87-6202e955086a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>f53ad07a-9344-46d3-9ad0-8e59dbc1372f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'commercial_register' and @type = 'text' and @name = 'commercial_register']</value>
      <webElementGuid>7f53fe46-10cf-4a54-9085-23cbe8b1d8c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
