<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__address_en</name>
   <tag></tag>
   <elementGuidId>d10cc38b-4e48-41fe-8206-729c7319e92b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_en</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_en']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8c3bec3-c6a0-493e-b018-f299d1ee2a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_en</value>
      <webElementGuid>fa5b2cc9-15cf-4816-94e8-46f64986d5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7eeb9dea-9387-42be-8d64-d8ea5094ff05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ed9c091-2597-46d7-a186-48df8b781446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address_en</value>
      <webElementGuid>e85ccd7b-6c6c-4c68-8645-ffb6be0165bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>elmnofia</value>
      <webElementGuid>f109b69b-d4e8-4114-a83a-eeae84ca3a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_en&quot;)</value>
      <webElementGuid>2261a83e-945c-4d4e-b9e7-77a89233a394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_en']</value>
      <webElementGuid>10b6e2c4-3269-4953-b7a1-8c527d5c1e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/form/div[7]/div/input</value>
      <webElementGuid>43222268-1acc-4552-86a1-e122d0770927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>6e97acb8-41b0-49af-8ab4-e26259291bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address_en' and @type = 'text' and @name = 'address_en']</value>
      <webElementGuid>4dc945d2-d769-4155-9e82-6380ec41638f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
