<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__governorate</name>
   <tag></tag>
   <elementGuidId>97e5745d-c323-400c-9b69-140f682180c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#governorate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='governorate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4db5a771-18b8-447b-9764-c4b4d831aa98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>governorate</value>
      <webElementGuid>a496f6f4-d039-4578-beeb-3865f48d0848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6763db21-12e3-4e21-815e-c5d5b22f358e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e724925-2fc7-41c6-b47e-01f2814016bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>governorate</value>
      <webElementGuid>c4e7fb3b-3e1e-4ce2-bb97-6fcdef266d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>المنوفية</value>
      <webElementGuid>7e11a107-c2f7-433e-a6d9-0c28e0f7dbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;governorate&quot;)</value>
      <webElementGuid>fb8afbbd-89bc-4915-8d87-5f92374407f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='governorate']</value>
      <webElementGuid>92c18857-7988-45ef-ab50-7bc3e9d5e354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/form/div[5]/div/input</value>
      <webElementGuid>7c26d000-7aef-44de-b0b3-cd32cc49991b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>3b81e5df-1e15-4498-a219-55ee54abe63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'governorate' and @type = 'text' and @name = 'governorate']</value>
      <webElementGuid>edbf6a12-4092-4b90-8686-4ab26e6586e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
