<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>43a99ed4-e51e-441c-9b4a-d3a5b26474fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#receipt_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='receipt_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8ebb151b-7173-46d9-8004-3d8779c4741f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receipt_number</value>
      <webElementGuid>753020a6-a7bd-40b8-a205-fd5b5b099bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>receipt_number</value>
      <webElementGuid>46508a10-847e-4e3b-8bf5-e77d717db425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control chosen-select </value>
      <webElementGuid>1803617d-1543-4116-936c-31f2787c03f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                اوتوماتيكى
                                يدوى
                            </value>
      <webElementGuid>522a292f-5cd6-436e-b26a-926b69e17727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receipt_number&quot;)</value>
      <webElementGuid>8ededc0c-6243-4d42-b10e-24501c09817b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='receipt_number']</value>
      <webElementGuid>950f3912-4607-4ee2-875d-7fd2f440bee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/form/div[16]/div/select</value>
      <webElementGuid>911d903c-4eb7-439b-b7be-7502ef8a58f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ترقيم سندات الدفع'])[1]/following::select[1]</value>
      <webElementGuid>c4c4a5a9-e4d0-4177-9c26-e2bda3219f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ترقيم التفريغ'])[1]/following::select[2]</value>
      <webElementGuid>d91281b3-cdb9-4f6c-8175-4268c4e19e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الضرائب فى طباعة العقد'])[1]/preceding::select[1]</value>
      <webElementGuid>138687e2-4d29-4b09-8e36-72753f087ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نظام المواعيد'])[1]/preceding::select[2]</value>
      <webElementGuid>aa1f4718-4ba9-4fe4-9407-dd2da202ad72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/select</value>
      <webElementGuid>4a20179a-c947-4bba-b611-6b3e95ce6c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'receipt_number' and @name = 'receipt_number' and (text() = '
                                اوتوماتيكى
                                يدوى
                            ' or . = '
                                اوتوماتيكى
                                يدوى
                            ')]</value>
      <webElementGuid>14725d83-959d-4d37-976f-74cc8d198fc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
