<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>5b305071-73b3-4752-9a8e-4a0535190faf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tax_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tax_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4c302cbb-ca77-488c-8401-01a1c5eed073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tax_type</value>
      <webElementGuid>ddf21a73-d8a6-4b2a-bd34-e6a0b3ddcdd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tax_type</value>
      <webElementGuid>efa4305c-e1f6-4bec-8842-aa9be0583288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bbebf737-96e9-4825-a6ed-2a512167fb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            اختر
                            نسبه
                            مبلغ ثابت
                        </value>
      <webElementGuid>05a88259-9cef-40c8-9582-ed15b4477c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tax_type&quot;)</value>
      <webElementGuid>658fae54-29fa-4138-81be-ca8c62705e1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tax_type']</value>
      <webElementGuid>f0f088f4-79cb-49ce-8471-7b7146179afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add_from']/div[3]/div/select</value>
      <webElementGuid>6a105699-c2b2-4a7c-8d04-9257b7e43779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نوع الضريبة'])[1]/following::select[1]</value>
      <webElementGuid>169eff20-900a-4631-b255-c755634f6f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نشط /غير نشط'])[1]/following::select[2]</value>
      <webElementGuid>676034a8-8ba0-44b4-88f8-fd77465946d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قيمة الضريبة'])[1]/preceding::select[1]</value>
      <webElementGuid>b2a10c2a-fa04-4938-9a07-56338b65970b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حفظ'])[1]/preceding::select[1]</value>
      <webElementGuid>daab8a0d-c8c0-4048-b922-ec545ed28474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>1e049079-08d6-4f18-b36a-df3287d605c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tax_type' and @id = 'tax_type' and (text() = '
                            اختر
                            نسبه
                            مبلغ ثابت
                        ' or . = '
                            اختر
                            نسبه
                            مبلغ ثابت
                        ')]</value>
      <webElementGuid>5a1ade80-0930-43a5-8eb9-c72588861bc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
