<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1 (1)</name>
   <tag></tag>
   <elementGuidId>2af6f391-bb76-43aa-be57-9ae8675f571c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.add_balance.btn.btn-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='removable2']/td[10]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92432638-1a21-432c-872c-06dcc58e721b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientname</name>
      <type>Main</type>
      <value>سعفان</value>
      <webElementGuid>a01e6506-ef2d-4bb9-a365-812ef9dbda2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fbc52b43-752a-40b1-9c89-0c464e2b3925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_balance btn btn-info</value>
      <webElementGuid>15a6f77f-0012-49df-a5a1-38d5c9535ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اضافة رصيد</value>
      <webElementGuid>0f0f6797-b341-492c-9950-3fcf69b9746b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;removable2&quot;)/td[10]/button[@class=&quot;add_balance btn btn-info&quot;]</value>
      <webElementGuid>e982ef91-8683-425e-9a08-085fae06a8d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='removable2']/td[10]/button</value>
      <webElementGuid>a33676d0-9eb2-464b-a439-98c086243301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نشط'])[1]/following::button[1]</value>
      <webElementGuid>be797d6b-ee67-406c-a412-ab0e129332e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الجبيل'])[1]/following::button[1]</value>
      <webElementGuid>690d03f4-84a4-40e9-af3f-c6f264917ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سحب رصيد'])[2]/preceding::button[1]</value>
      <webElementGuid>76354af6-7057-462b-b2ad-095eeeb3fbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تعديل'])[1]/preceding::button[2]</value>
      <webElementGuid>2be9d3a9-a1c9-4a62-b6b1-5daf61bebbab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/button</value>
      <webElementGuid>75e1b5e8-b3a7-4f78-8133-de2bb4c0073f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'اضافة رصيد' or . = 'اضافة رصيد')]</value>
      <webElementGuid>cb2d2032-9db5-4a80-92d2-3521cc663cee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
