<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2_3</name>
   <tag></tag>
   <elementGuidId>d8b52986-ea29-456e-8aba-47ae04450a83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.withdrawal_balance.btn.btn-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='removable2']/td[11]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4a73daf-070e-4f1c-bf43-0fb601f2a1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientbalance</name>
      <type>Main</type>
      <value>46,000.00</value>
      <webElementGuid>c1dd92bd-ac54-4da0-bf12-47997a23fba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientname</name>
      <type>Main</type>
      <value>سعفان</value>
      <webElementGuid>5e0479e0-a2e5-43a6-bda0-2c1ef72d2133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clientid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5bb9fdae-ab72-4599-b3ff-80305f475e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withdrawal_balance btn btn-danger</value>
      <webElementGuid>eb21b157-71cb-432d-8232-f0f166e3e2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>سحب رصيد</value>
      <webElementGuid>d9808f95-79f6-4355-adf3-f6c3fa605505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;removable2&quot;)/td[11]/button[@class=&quot;withdrawal_balance btn btn-danger&quot;]</value>
      <webElementGuid>02d706a8-235f-4198-8691-21e4d7143669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='removable2']/td[11]/button</value>
      <webElementGuid>838b25ab-0a4d-4334-9fe2-710f13a16ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اضافة رصيد'])[2]/following::button[1]</value>
      <webElementGuid>a26ab4df-d712-41be-b9b2-9a78493cdc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نشط'])[1]/following::button[2]</value>
      <webElementGuid>f0ba120a-ddf4-48af-b6d5-058b52a48c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تعديل'])[1]/preceding::button[1]</value>
      <webElementGuid>9e8a896b-fd92-4fbb-a99e-34967a4df8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تغيير الحالة'])[1]/preceding::button[1]</value>
      <webElementGuid>34fd409b-4684-4786-a73d-13fa7ef19026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/button</value>
      <webElementGuid>ad2a841b-4ba6-4de3-bbb6-ab8e4d548186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'سحب رصيد' or . = 'سحب رصيد')]</value>
      <webElementGuid>404b7b5e-e029-4380-84b3-0aa0c5ceb963</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
