<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ (1)</name>
   <tag></tag>
   <elementGuidId>309a0107-8627-4467-b708-ae6513932541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.block.full-width.m-b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a019b9f3-3aae-48a9-8544-f8f3298a10d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e377072e-39be-48c6-9c6b-13e1e1c13105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn  block full-width m-b</value>
      <webElementGuid>a362b262-cc28-4a7a-a938-9189c28d4190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    دخول
                </value>
      <webElementGuid>9023e371-12fe-4e80-845f-d1d61b68ca8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[@class=&quot;py-4&quot;]/div[@class=&quot;middle-box text-center loginscreen animated fadeInDown&quot;]/div[1]/form[@class=&quot;m-t&quot;]/button[@class=&quot;btn  block full-width m-b&quot;]</value>
      <webElementGuid>7385cd74-e809-4ba9-9d5b-da104cf8baff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>89e0443e-455d-4cef-ad43-b21ca678d335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/div/form/button</value>
      <webElementGuid>c3742b83-8d70-4d0a-b795-4e7cc1a07675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='كلمة السر'])[1]/following::button[1]</value>
      <webElementGuid>17328543-5fd6-49ac-8b0e-290ab8cce561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم المستخدم'])[1]/following::button[1]</value>
      <webElementGuid>1753e769-aa61-4318-9338-741f86b43b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جميع الحقوق محفوظة © 2023'])[1]/preceding::button[1]</value>
      <webElementGuid>0dca249c-af55-45bb-9bb8-f48a20aa8660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='دخول']/parent::*</value>
      <webElementGuid>54671426-1569-40a7-abec-aebc0c0d771e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8e1c2ffc-e18b-4a1b-940f-1c5b891da4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                    دخول
                ' or . = '
                    دخول
                ')]</value>
      <webElementGuid>f0472c34-4cad-4f3d-a91f-8f06d0c5dfe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
