<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>6ea60f29-2704-45cb-b3ad-7b02da6bc3d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save_print</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save_print']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9d63fcc-2b88-4c52-b199-4dc45e78c2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 btn btn-success</value>
      <webElementGuid>9aa66e36-0190-4b22-b0dd-307d3d247eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a7b5c810-3dc5-48c1-bc23-c9951a81c244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_print</value>
      <webElementGuid>b93db716-7c60-43cc-9d81-0abbc50f3142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>حفظ
            </value>
      <webElementGuid>00c76d56-bc51-4a43-a436-41b4a1d4ec6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save_print&quot;)</value>
      <webElementGuid>91455c36-6341-4370-b36c-9f7bcfbab916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save_print']</value>
      <webElementGuid>141de7b6-6d11-42c7-8a68-59dc86f94fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/form/button</value>
      <webElementGuid>852060c3-ad8f-436c-b943-c92e71521f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='خزينة الريان شبكة'])[1]/following::button[1]</value>
      <webElementGuid>0b7100ed-233e-4880-97ae-2639b40baf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='خزينة الريان النقدية'])[1]/following::button[1]</value>
      <webElementGuid>1fd3eab7-d8cb-4739-a54f-54dffb77d906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'save_print', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>02488ca0-92de-4882-b202-c09e3f47446b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='حفظ']/parent::*</value>
      <webElementGuid>1b33f985-fe64-4eae-b7c0-784d3cd1049f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ec0cfb68-13a7-4762-9632-735c178f06f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'save_print' and (text() = 'حفظ
            ' or . = 'حفظ
            ')]</value>
      <webElementGuid>10fb81e8-29c7-4e98-bfd9-8be6c7714259</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
