<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_31</name>
   <tag></tag>
   <elementGuidId>11092bbd-ad57-461f-837a-d30c1e145cbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'31')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a08c751-a529-4885-8d7f-6094fe2c9226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>58a75ad9-e96c-43ff-ac7c-d6accc766988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jd2460156.5 calendars-highlight</value>
      <webElementGuid>69b6b85f-761e-4ca6-ba8a-1760a197cfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>اختر Mon, Jul 31</value>
      <webElementGuid>bf9614fc-9569-4af3-acc5-027bd5b4f0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>4184b453-b27c-4f13-a719-efad4631a58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done&quot;]/div[@class=&quot;calendars-popup&quot;]/div[@class=&quot;calendars calendars-rtl&quot;]/div[@class=&quot;calendars-month-row&quot;]/div[@class=&quot;calendars-month&quot;]/table[1]/tbody[1]/tr[6]/td[2]/a[@class=&quot;jd2460156.5 calendars-highlight&quot;]</value>
      <webElementGuid>57a3262c-2bc2-4eb5-9f08-49c9b996b179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'31')]</value>
      <webElementGuid>7b6d3bef-7067-4449-9e3d-75c8d154643b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[31]</value>
      <webElementGuid>33c4c077-2a52-403c-b512-b255b0fbf0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::a[31]</value>
      <webElementGuid>66666b83-f085-41ad-8d1d-f789cfcc8c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مسح'])[1]/preceding::a[1]</value>
      <webElementGuid>7cfab8ec-73e9-4c20-bb8d-ae8fb413ef53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إغلاق'])[1]/preceding::a[2]</value>
      <webElementGuid>edc3bbe8-f122-4cc9-9400-cd68ce5f7880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>a3f5b766-f1d0-4cb7-b91d-55e3d765018a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[35]</value>
      <webElementGuid>e210275e-d4d9-4ebe-9133-f8876e966c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/a</value>
      <webElementGuid>b03f6728-f1b6-412e-a1ee-88e8885f33f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @title = 'اختر Mon, Jul 31' and (text() = '31' or . = '31')]</value>
      <webElementGuid>c5d8d2f5-37cd-470c-ab31-b1f8eb24d484</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
