<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__addContainerSizeList</name>
   <tag></tag>
   <elementGuidId>dcf3a15e-894b-4656-bcc6-c076bc53df76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addContainerSizeList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addContainerSizeList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb7c3549-6f62-462f-a239-4f13b3e950ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success </value>
      <webElementGuid>d6008d78-7aa3-4a85-aebf-0404a5bd6458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addContainerSizeList</value>
      <webElementGuid>aa83d1de-d671-4217-9fc1-d209a21014de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addContainerSizeList&quot;)</value>
      <webElementGuid>ac883f6f-d20c-4014-9979-5911867c8cb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addContainerSizeList']</value>
      <webElementGuid>c50ce2e3-3bb7-4a9a-a669-fd4f6e7e7b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_containers']/div[6]/a</value>
      <webElementGuid>3959a6d2-ba6a-46ae-8f52-64a3d07b1e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاجمالي'])[1]/following::a[1]</value>
      <webElementGuid>f0e57d2d-586c-45a6-94cc-cf26450a283e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='السعر'])[1]/following::a[1]</value>
      <webElementGuid>195ff7a6-bc1f-48ba-a87c-eebeb8fb6e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='يجب الضغط على زر الاضافه للتاكيد'])[1]/preceding::a[1]</value>
      <webElementGuid>161b3195-c058-4011-a582-dbf50229d578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الحاويات المطلوبه فى التعاقد'])[1]/preceding::a[1]</value>
      <webElementGuid>93ec31c1-8294-425e-bbca-8596df3610ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>4b70dfd4-535a-4bb4-b42d-4974470c0c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addContainerSizeList']</value>
      <webElementGuid>6f1595a2-e74a-4a77-b005-41f7222f0215</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
