<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_admin</name>
   <tag></tag>
   <elementGuidId>2759d471-1017-4778-b86f-4ed40dba8b49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navbarDropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navbarDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>726e9021-5220-4d13-9da8-2dd2f9f5f287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbarDropdown</value>
      <webElementGuid>36d7c1bb-d024-44fa-b4e3-309c2266e1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link dropdown-toggle</value>
      <webElementGuid>7f2b272b-552a-4925-b8ee-5c5fcde90f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>96bbb65f-06bf-4f25-8080-ba0e66706baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a54a323b-4ff8-4ee9-a743-5cae07b27c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>9fb1b980-2b9f-40aa-8e71-46df9a6f192b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c4658306-ca61-4524-a48a-85c9a7f57b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c295f4c3-be3d-41c9-b1a3-c74f1439772c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    admin 
                                </value>
      <webElementGuid>9c5d357e-6a15-4186-97d6-979fc7474916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarDropdown&quot;)</value>
      <webElementGuid>9cbcef12-a00a-497a-9473-6adcd2df64c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navbarDropdown']</value>
      <webElementGuid>04f22103-6ba3-4cc3-af0b-ba8d4ff4e34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/nav/ul/li/a</value>
      <webElementGuid>5d4f8652-cd2e-4a88-bf42-c5a1228d7005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'admin')]</value>
      <webElementGuid>4f50c21a-700d-4d32-98bd-ca75f3e8f124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تقرير حركة الخزنة'])[1]/following::a[2]</value>
      <webElementGuid>4d94d515-cebc-4009-96a5-ec5f824828e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التحويل بين الخزن'])[1]/following::a[3]</value>
      <webElementGuid>b6a698fc-da8b-462f-9683-c60264762685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل خروج'])[1]/preceding::a[1]</value>
      <webElementGuid>af93d3ad-a2c4-400c-836e-d1695823cf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طباعة عقد'])[1]/preceding::a[2]</value>
      <webElementGuid>e45bdf59-e9e9-4641-ae49-6281aa823406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='admin']/parent::*</value>
      <webElementGuid>d0f201c7-dfc4-4bee-b06e-72abe4f2af57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[16]</value>
      <webElementGuid>6edfe16f-724b-4e89-8f75-f02cb712113d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li/a</value>
      <webElementGuid>187b526f-c062-44db-bc75-0db989275846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'navbarDropdown' and @href = '#' and (text() = '
                                    admin 
                                ' or . = '
                                    admin 
                                ')]</value>
      <webElementGuid>87d6f2a1-430b-4d8f-8fe4-95ade9e414dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
