<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>c40a3957-0ac0-46e1-a145-ad418899f9ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save_print</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save_print']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f84e9a8-b140-4784-9c87-76b748ce8f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 btn  btn-success</value>
      <webElementGuid>dcb3059e-e513-44f7-8f0c-1caac9a42bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_print</value>
      <webElementGuid>224226f1-dc19-490a-8d33-ddf669676712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3e485f0b-36a1-421b-8cc8-ff587d8a14c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>حفظ
                </value>
      <webElementGuid>81bdaed5-3965-4f0a-8f00-467c2b77f143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save_print&quot;)</value>
      <webElementGuid>43fec621-5c3f-40f4-9fe0-85f7fc2aaa8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save_print']</value>
      <webElementGuid>3e3b2667-553f-45e4-a933-2850a01b7d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[2]/form/div[11]/button</value>
      <webElementGuid>4d8b71e8-dfbf-413f-a0ff-7be93d9b2c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ملاحظات'])[1]/following::button[1]</value>
      <webElementGuid>eaa27f48-a62f-474a-a314-928a864cb0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الى'])[1]/following::button[1]</value>
      <webElementGuid>e71fe50a-3e30-4621-bb85-659d18536122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'save_print', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>a9f101e6-dcc4-441e-956c-1e6862166dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='حفظ']/parent::*</value>
      <webElementGuid>ece20265-07f2-49ea-bff8-4815e039b576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/button</value>
      <webElementGuid>e304fa40-52aa-49aa-9e8c-03fe6d79737e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'save_print' and @type = 'submit' and (text() = 'حفظ
                ' or . = 'حفظ
                ')]</value>
      <webElementGuid>ff6be004-7714-4147-b12e-499d001894a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
