<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__fa fa-plus</name>
   <tag></tag>
   <elementGuidId>90691891-d09c-466f-ab40-1f64508f7ffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addContainerSizeList > i.fa.fa-plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addContainerSizeList']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a70d0cee-d273-46e4-9139-843a5c9694d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>eb38109f-347f-47ed-b69e-a6a96a14b02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addContainerSizeList&quot;)/i[@class=&quot;fa fa-plus&quot;]</value>
      <webElementGuid>0801d830-9406-479c-be4f-d1497f7142dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='addContainerSizeList']/i</value>
      <webElementGuid>4a8e09fe-eb2d-449e-a26f-525e25baf36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/i</value>
      <webElementGuid>7b2f6801-f882-476e-b2c2-28c2b59f1ff7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
