<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__trip_days</name>
   <tag></tag>
   <elementGuidId>d13c5c17-67b9-4ff4-b5fe-146ae5ced78b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trip_days</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='trip_days']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca476bd3-f072-4783-b357-f4a3e9f81d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trip_days</value>
      <webElementGuid>9b1a4acc-7bb5-4a9b-97fd-048d1491795c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trip_days</value>
      <webElementGuid>0593bb1a-bd10-48c6-9827-970926f5c520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-control</value>
      <webElementGuid>4b44f669-0e10-4042-b696-3a2f75806d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6b26ce14-39b8-49dc-8c6d-f7d2460808dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5f989f04-9ed7-437f-af1c-e1d2dc2ad319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trip_days&quot;)</value>
      <webElementGuid>16058b57-af22-4fb2-9abc-a99a87cd0736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='trip_days']</value>
      <webElementGuid>ced980d4-2dbf-4a40-8983-653fb386278a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trip_duration']/div/input</value>
      <webElementGuid>0b402578-43f0-480e-badd-ae42b35abbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>c28785f5-f061-408a-a641-d6e9dc62cd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'trip_days' and @name = 'trip_days' and @type = 'number']</value>
      <webElementGuid>7592b326-7c52-4376-89ef-83dcad96a9a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
