<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__driver_commission</name>
   <tag></tag>
   <elementGuidId>eb1d56ce-886c-45ec-a7c7-0e1616e2bda4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#driver_commission</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='driver_commission']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58ee59c2-0e64-4fd1-8227-b5c5c08be645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>120919fa-d5b7-4815-a1d0-ad0149608cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b337512-2af5-4cda-a130-19cbffdb8a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>driver_commission</value>
      <webElementGuid>74ab281d-d3d3-40b6-ae44-ae4c277e2b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>driver_commission</value>
      <webElementGuid>4708179a-da9d-411b-9cb0-ae456ba58167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5145e137-c79c-43d6-a5c2-644cd3bcc663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('please enter driver commission')</value>
      <webElementGuid>d80823ec-57b0-4b27-924e-c18cf45ab159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>b5fc6a67-00bb-4e4c-8ed3-253705641457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;driver_commission&quot;)</value>
      <webElementGuid>404b9820-61aa-46f7-89ae-b031ef679b6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='driver_commission']</value>
      <webElementGuid>e0f6a319-f9d3-43a6-9762-658c5502d313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-cash']/div[8]/div[9]/div[2]/input</value>
      <webElementGuid>7c361dcc-7d04-4ee2-8968-7f3d99fe0e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input</value>
      <webElementGuid>538f3a75-5502-4181-a18c-8e987dc1520d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'driver_commission' and @name = 'driver_commission']</value>
      <webElementGuid>e286ebbd-c3ef-4fef-aa63-194efa3f1799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
