<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__supervisor_commission</name>
   <tag></tag>
   <elementGuidId>cda4f480-61a1-40d3-bf86-196136ba9178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#supervisor_commission</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='supervisor_commission']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcd46c93-be8b-4c3f-9487-b29f8de0029f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c0dc4a2f-1aba-4a93-b60c-719c20d4a48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cac183ff-7118-4fed-a5ec-f40f3c8b30d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supervisor_commission</value>
      <webElementGuid>8838db42-7f63-4c19-b1b7-b7a06f105b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>supervisor_commission</value>
      <webElementGuid>660325b5-27c9-4b30-9135-ce48cf194575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>26766042-a795-4d0f-ab47-e9a82be8355e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('please enter supervisor commission')</value>
      <webElementGuid>cd8ce7a5-34cd-4540-a133-664266ed2955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>798c7ea1-dd4f-44d6-a0b8-4a2ec66deea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supervisor_commission&quot;)</value>
      <webElementGuid>8cb60a7f-dabb-44f7-91f3-f2b29b22fba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='supervisor_commission']</value>
      <webElementGuid>acaa9e9a-925f-4815-9d71-17a3b740916c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-cash']/div[8]/div[8]/div[2]/input</value>
      <webElementGuid>8e8dd3f2-f6fb-4efe-8be4-cc87d6fb989f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/input</value>
      <webElementGuid>44200af7-0e9d-4a91-9c42-c15755696fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'supervisor_commission' and @name = 'supervisor_commission']</value>
      <webElementGuid>f4f57cd8-3f8e-4545-a173-519bbc0d3db8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
