<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__payment_method_1</name>
   <tag></tag>
   <elementGuidId>91d8f988-ecb5-48db-8911-aa94b8550b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment_deferred</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_deferred']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54178cca-7fe8-4e3b-afc5-74867fdb3005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_deferred</value>
      <webElementGuid>c6dc8d42-4444-4d6a-859d-9a7ed38259d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>474a6511-616e-4cbd-9b43-fc79c1daa104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment_deferred form-control</value>
      <webElementGuid>5769ba63-1a7d-4fb0-aedf-f59d0ee335b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>74b1aaf5-93af-41ff-be19-f82b73205d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>deferred</value>
      <webElementGuid>b4c5277b-7794-4f87-b091-224337a4bce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_deferred&quot;)</value>
      <webElementGuid>e815bab3-2071-418d-bd47-670a573cf6b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_deferred']</value>
      <webElementGuid>ce0eecb8-0d55-4802-b3cf-efb90712e089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-cash']/div[8]/div[6]/div/div[2]/input</value>
      <webElementGuid>8aa4bd95-f351-4065-8d21-9c62887fc9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/input</value>
      <webElementGuid>ec835007-8d69-4a77-a0a1-8c263caeb4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_deferred' and @name = 'payment_method' and @type = 'radio']</value>
      <webElementGuid>e54c6d5a-8ba3-4176-b571-695d48b61f55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
