<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__size_trips</name>
   <tag></tag>
   <elementGuidId>6b681e0f-c695-4800-8681-3a05999e8b83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#size_trips</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='size_trips']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3610b4e-cf65-41c0-8ef8-2e217275c8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size_trips</value>
      <webElementGuid>b037c6d1-cf54-41cc-a133-49e1ebf96886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size_trips</value>
      <webElementGuid>bb3f46e2-d2f7-41d6-af34-0c7001f4dbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cf9d6d5d-c398-41e3-8873-e5e75d4a9194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>03578804-0e33-4bcd-9b08-2130f930025e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size_trips&quot;)</value>
      <webElementGuid>674089aa-702d-4619-8fa2-5ab81e95207a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='size_trips']</value>
      <webElementGuid>fb9a466a-f2ca-4a9e-8e76-6afd76bd885f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_containers']/div[3]/div/input</value>
      <webElementGuid>33d59729-7fda-45b6-a60f-562c9717905d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>cbe5b686-b16d-4043-b5e5-9b01f9192779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'size_trips' and @name = 'size_trips' and @type = 'number']</value>
      <webElementGuid>67de436d-0b91-4f07-8e50-4dbb1cef121a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
