<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__from_date_1</name>
   <tag></tag>
   <elementGuidId>4ce8533e-099c-40f3-838b-0ec79bdfb8fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from-date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from-date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc9b6269-db33-49b0-9c97-10054726e21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb9f95b4-0d85-4a38-8b8e-f98813ae3a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control picker is-calendarsPicker</value>
      <webElementGuid>52348bb8-cc27-42be-aac7-0ce87bc8b59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from-date</value>
      <webElementGuid>69c81b29-a7c7-4915-9cf1-85560aa2cb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>from_date</value>
      <webElementGuid>adc6e5a9-fe69-4a0b-af08-1a997829dfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from-date&quot;)</value>
      <webElementGuid>cbf10a3d-8c2e-4661-bf39-cd00512b8b33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from-date']</value>
      <webElementGuid>02c05dc6-c089-4d3f-b4b3-68d44ca9bf4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='rent-duration']/div/div/div/div/input)[2]</value>
      <webElementGuid>f05eb136-f225-458d-a491-d8537c5d75ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/div/div/div/input</value>
      <webElementGuid>16111aa8-5616-4d6a-b88c-97e7b92dffe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'from-date' and @name = 'from_date']</value>
      <webElementGuid>b8813f9c-69ac-4fa5-aa8a-dad724f0391d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
