<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__payment_method</name>
   <tag></tag>
   <elementGuidId>5aad3216-c631-4ae8-bbe0-29b0e055f310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment_cash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_cash']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2b13c3f-7455-449c-8bd6-848b9a578533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_cash</value>
      <webElementGuid>44f3ec70-6521-4f70-a614-9a67f3c386a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>fc954ff6-50b0-49c9-9f6e-9edff9c1b0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment_cash form-control</value>
      <webElementGuid>e6d16fb9-976f-44c9-a67d-0eee1fa4974d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2737b005-517b-4161-8f59-6e637191f87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>cash</value>
      <webElementGuid>6f329e82-c1c9-48ab-9135-f1d4cf27c0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_cash&quot;)</value>
      <webElementGuid>812939dd-8dc0-44e2-9c2e-9509999c74bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_cash']</value>
      <webElementGuid>00603100-701e-476a-8192-cf4557961acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-cash']/div[8]/div[6]/div/div/input</value>
      <webElementGuid>1ffd7112-fa04-448d-bb32-5fce0379ed76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>3fd642f1-4a82-467a-84cb-bcaad4caa0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_cash' and @name = 'payment_method' and @type = 'radio']</value>
      <webElementGuid>cc40aa59-dbc7-4c03-8409-dc9f81610bab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
