<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>main_2023</name>
   <tag></tag>
   <elementGuidId>9213294d-37cc-4826-8bcb-a01426098678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>main.py-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>f3185129-233b-428b-aa21-3c6840415f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-4</value>
      <webElementGuid>f00bb072-1012-438c-ad7d-598cacf3a16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  مرحبا بك فى برنامج اداره الحاويات يرجى تسجيل الدخول   اسم المستخدم  كلمة السر  
                    دخول
                 جميع الحقوق محفوظة © 2023</value>
      <webElementGuid>12ccb963-8b4d-49ce-aa65-a70e09d378ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[@class=&quot;py-4&quot;]</value>
      <webElementGuid>3b1fa6a4-d232-405b-833c-895ab24b8dbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main</value>
      <webElementGuid>8021c1d8-05ca-444b-9b27-b1a67d257f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main</value>
      <webElementGuid>5db23a00-87f7-439f-ac55-d494f7b0c81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//main[(text() = '  مرحبا بك فى برنامج اداره الحاويات يرجى تسجيل الدخول   اسم المستخدم  كلمة السر  
                    دخول
                 جميع الحقوق محفوظة © 2023' or . = '  مرحبا بك فى برنامج اداره الحاويات يرجى تسجيل الدخول   اسم المستخدم  كلمة السر  
                    دخول
                 جميع الحقوق محفوظة © 2023')]</value>
      <webElementGuid>f9b8d11c-ce14-458e-b565-80e8908a2d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
