<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_20  30_1</name>
   <tag></tag>
   <elementGuidId>9ccebfd4-8efb-4ce5-b995-14cdd86505e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#size_id2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size_id2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f91df26c-268b-4eec-b2d6-d8a9aa32dfb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size_id2</value>
      <webElementGuid>e6f52297-d2ba-4b5e-aa5f-dfa7a1313f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>c1d8afff-4b64-44bb-a595-72493459ed54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control chosen-select size_id</value>
      <webElementGuid>b2c21eaf-956f-470a-b851-0577cb676c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برجاء اختيار الحجم20 يارده 30 يارده </value>
      <webElementGuid>ced2befa-22fb-417a-b915-6cedbb2c07f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size_id2&quot;)</value>
      <webElementGuid>3f3705f1-685d-417e-8ced-5fde57290cd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size_id2']</value>
      <webElementGuid>e5752913-a71c-4778-8f9c-6957c03f4e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-cash']/div[3]/div/select</value>
      <webElementGuid>39fb6c03-1f2e-443d-9218-f07445d0455a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[2]/following::select[1]</value>
      <webElementGuid>4219656b-ad19-402b-b73a-9ba1ffd7c4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[2]/following::select[2]</value>
      <webElementGuid>212bae3e-d1a4-4f70-ae47-7eaaa16453a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم الحاوية'])[2]/preceding::select[1]</value>
      <webElementGuid>355ebf23-2b79-43db-a027-58b8ede561e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم العميل'])[1]/preceding::select[2]</value>
      <webElementGuid>6e8ecf3d-a9a8-4e89-80e4-ae8cb1b16354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div[3]/div/select</value>
      <webElementGuid>5e291908-cb2e-47b0-ae71-2a771a6cbece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size_id2' and @name = 'size_id' and (text() = 'برجاء اختيار الحجم20 يارده 30 يارده ' or . = 'برجاء اختيار الحجم20 يارده 30 يارده ')]</value>
      <webElementGuid>f6c19c5e-5727-4239-885c-767b6ae8b89c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
