<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>d841b285-f04c-42bf-8f82-a03f80689814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='client_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cf509a97-8ee7-437f-99d0-d15b87a167ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker form-control</value>
      <webElementGuid>d31b8cf8-2953-44f4-bd53-1834bc3d7f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-live-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f397f5b0-95cd-4cf6-bde7-403ea8de6382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ca402d74-63aa-4924-810a-5d6e72f97c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>client_id</value>
      <webElementGuid>20aa2ba1-911f-4e15-be5d-5c7c66f07a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client_id</value>
      <webElementGuid>80e72c9f-390b-45d7-9ac0-fdd3098acd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>إختر من قائمة العملاء ..</value>
      <webElementGuid>fa2b8342-cef1-40a1-9bb0-621310352815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>2891659f-915a-4e5f-b922-6960c58d554f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إختر من قائمة العملاء ..
                                                                                    شعبان
                                                            سعفان
                                                            نعمان
                                                                        </value>
      <webElementGuid>eb5105ee-3bf9-45f2-985b-d730cd91e3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client_id&quot;)</value>
      <webElementGuid>84dac934-1cd0-47c4-9e9f-263f2fb79521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client_id']</value>
      <webElementGuid>d8512608-7bd3-4e5d-8855-5e138e1f6c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[2]/form/div[2]/div/div/select</value>
      <webElementGuid>41e319a5-b75e-41b6-a8b1-8e5b1c25d8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نعمان'])[1]/following::select[1]</value>
      <webElementGuid>b7502350-4869-4d5e-a290-4f4d36cba5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سعفان'])[1]/following::select[1]</value>
      <webElementGuid>90b6d21a-22cd-4875-9505-ca38d1f5f46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إضافة عميل'])[2]/preceding::select[1]</value>
      <webElementGuid>26b01754-6f59-431e-a52f-db2dfa0773bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الموقع'])[1]/preceding::select[1]</value>
      <webElementGuid>3b21b4df-841a-42c0-944a-c8024d0a5978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>e2761354-91f9-4f73-b3c3-b0e130822db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'client_id' and @id = 'client_id' and @title = 'إختر من قائمة العملاء ..' and (text() = 'إختر من قائمة العملاء ..
                                                                                    شعبان
                                                            سعفان
                                                            نعمان
                                                                        ' or . = 'إختر من قائمة العملاء ..
                                                                                    شعبان
                                                            سعفان
                                                            نعمان
                                                                        ')]</value>
      <webElementGuid>b0a9e552-4041-45e1-99d9-17e4200fc8ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
