<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1</name>
   <tag></tag>
   <elementGuidId>3d535142-430f-4b17-9a99-d5a3521c62e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#classification_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='classification_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7bf9c57b-0a59-48fe-bc16-008308b53e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control classification_id</value>
      <webElementGuid>89820371-6100-4b3a-b52a-48dd6762a328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>classification_id</value>
      <webElementGuid>12b1181c-887e-49fb-b893-da0ff5734a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>classification_id</value>
      <webElementGuid>42fad623-e191-42ce-bfb1-19c28501c0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('please select classification')</value>
      <webElementGuid>6d4c833d-f156-428f-8b38-d96df64f37f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>d1aeab4b-8730-40b4-bbea-194bf4115c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            برجاء اختر التصنيف
                                                            نفايات
                                                            انقاض
                                                    </value>
      <webElementGuid>b69a8e55-8f1b-4017-95a9-9b5f3c3a1fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;classification_id&quot;)</value>
      <webElementGuid>dbf00778-264e-4613-b7f6-5f548c111a9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='classification_id']</value>
      <webElementGuid>e2028774-4b41-483a-bddd-365f57a05fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_containers']/div/div/select</value>
      <webElementGuid>6a78a470-284b-4f43-8cdd-45e8889bad7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[1]/following::select[1]</value>
      <webElementGuid>72530bd3-32ed-4ed7-b01d-07164704a298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد المراحل'])[1]/following::select[1]</value>
      <webElementGuid>e4a1484c-5b0d-4508-a0ee-79c54980397a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[1]/preceding::select[1]</value>
      <webElementGuid>c74a6814-c273-4702-9029-e95abe2f6bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد الرحلات'])[1]/preceding::select[2]</value>
      <webElementGuid>250d75a0-6eec-456f-a039-0225d7494c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/select</value>
      <webElementGuid>66b540e2-4e60-4461-86a0-4ff81194d0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'classification_id' and @id = 'classification_id' and (text() = '
                            برجاء اختر التصنيف
                                                            نفايات
                                                            انقاض
                                                    ' or . = '
                            برجاء اختر التصنيف
                                                            نفايات
                                                            انقاض
                                                    ')]</value>
      <webElementGuid>a8fb9a1c-0fe2-4874-980d-b52bde87707b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
