<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_20  30_1_2</name>
   <tag></tag>
   <elementGuidId>f183012b-0343-499c-b8df-6154fb2b2490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#size_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1d872168-adcf-4c9c-b6f4-6acf5abef980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>9ac09890-8735-458b-bc4b-20aad5108af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>514b6bdc-facb-4593-b5df-e748d389b842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control chosen-select size_id</value>
      <webElementGuid>26d95e8d-5b29-467e-8983-f8c618768d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برجاء اختيار الحجم20 ياردة 30 ياردة </value>
      <webElementGuid>abf22209-37f0-4424-9ddb-7a50f20d0c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size_id&quot;)</value>
      <webElementGuid>b38d987d-8f97-4eb1-aa30-42ce0ccbf892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size_id']</value>
      <webElementGuid>43e73c5a-9de2-4e9f-ae62-d404da1f43f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_containers']/div[2]/div/select</value>
      <webElementGuid>55d5f6a2-d783-47e9-b2b1-ad26c94ac36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[1]/following::select[1]</value>
      <webElementGuid>ba598d71-77a9-49dd-b514-0b617b8455b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[1]/following::select[2]</value>
      <webElementGuid>55f0b544-3863-4dce-ac32-b018592e818d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد الرحلات'])[1]/preceding::select[1]</value>
      <webElementGuid>b152fdaa-e6a5-42a0-85ba-a2af53dbbf15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='السعر'])[1]/preceding::select[1]</value>
      <webElementGuid>f88859b0-d078-4ec8-8c87-7560b2837fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>33d45ed2-d9ae-477f-a33f-7dad994eeaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size_id' and @name = 'size_id' and (text() = 'برجاء اختيار الحجم20 ياردة 30 ياردة ' or . = 'برجاء اختيار الحجم20 ياردة 30 ياردة ')]</value>
      <webElementGuid>0913ad5b-5fcc-4ae9-a180-b5ec12ba47cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
