<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_20  30</name>
   <tag></tag>
   <elementGuidId>2e656683-dfaf-46b5-98e8-b10657eab131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#size_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e417dfea-e8e2-48dd-844e-d018abd862dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>81dc5f3e-c09b-4926-ae38-405ac9e2f925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size_id</value>
      <webElementGuid>d77fea52-4e82-4e81-abf0-d968783aba3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control chosen-select size_id</value>
      <webElementGuid>bb3f98f8-07c2-4275-948a-2f0b64d540e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برجاء اختيار الحجم20 ياردة 30 ياردة </value>
      <webElementGuid>3d2208bf-b977-49a0-85a4-ccd744a51a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size_id&quot;)</value>
      <webElementGuid>54e3d264-f0b6-4eed-a37f-ae022210ebce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size_id']</value>
      <webElementGuid>c9ef9f10-8a79-4ad9-a352-e2e07adc9165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_containers']/div[2]/div/select</value>
      <webElementGuid>37afdbdf-ee84-4b2b-879e-e5283722aeb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم الحاوية'])[1]/following::select[1]</value>
      <webElementGuid>2f39cfb6-3368-46d0-ba05-86240ccf7896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[1]/following::select[2]</value>
      <webElementGuid>9485bf9c-7fe2-41c8-9db2-6ffc102d6a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد الرحلات'])[1]/preceding::select[1]</value>
      <webElementGuid>7523704d-8a81-461c-9ba4-a20ec41b3da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='السعر'])[1]/preceding::select[1]</value>
      <webElementGuid>71a81711-6956-4e07-b946-2c9c8ac24f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>54b0e4d5-5a5f-4215-8eab-c3e1cf78914d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size_id' and @name = 'size_id' and (text() = 'برجاء اختيار الحجم20 ياردة 30 ياردة ' or . = 'برجاء اختيار الحجم20 ياردة 30 ياردة ')]</value>
      <webElementGuid>155a092c-8817-489f-8087-665d4c32f304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size_id' and @name = 'size_id' and (text() = 'برجاء اختيار الحجم20 يارده 30 يارده ' or . = 'برجاء اختيار الحجم20 يارده 30 يارده ')]</value>
      <webElementGuid>217f2219-1017-466b-a6d4-fa9acbff48c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
